#ifndef NetExportBaseNominal_EXISTS
#define NetExportBaseNominal_EXISTS

/**
@file  NetExportBaseNominal.hh
@brief NetExportBaseNominal GUNNS Basic Network declarations.


@details
PURPOSE: (Provides classes for the NetExportBaseNominal GUNNS Basic Network.)

REFERENCES:
  ()

ASSUMPTIONS AND LIMITATIONS:
  ()

LIBRARY DEPENDENCY:
  ((NetExportBaseNominal.o))

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.6.0) (2026-07-16 09:23:02.976195))

@{
*/

#include "software/SimCompatibility/TsSimCompatibility.hh"
#include "math/approximation/TsLinearInterpolator.hh"
#include "core/network/GunnsNetworkBase.hh"
#include ".hh"
#include "core/GunnsBasicCapacitor.hh"
#include "core/GunnsBasicConductor.hh"
#include "core/GunnsBasicExternalDemand.hh"
#include "core/GunnsBasicExternalSupply.hh"
#include "core/GunnsBasicJumper.hh"
#include "core/GunnsBasicPotential.hh"
#include "core/GunnsBasicSocket.hh"
#include "core/GunnsBasicSource.hh"
#include "core/GunnsBasicJumperPlug.hh"

// Forward-declare the main network class for use in the config data.
class NetExportBaseNominal;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportBaseNominal_Sockets Jumper Plug definitions
///
/// @details  Defines a jumper plug class for a socket list in this network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportBaseNominal_Sockets : public GunnsBasicJumperPlug
{
    TS_MAKE_SIM_COMPATIBLE(NetExportBaseNominal_Sockets);
    public:
        /// @brief  Enumeration of the socket options for this plug.
        enum SocketsEnum {
            GroundSocket = 0,
            NONE = 1
        };
        SocketsEnum mActiveConnection;     /**< *o (--) trick_chkpnt_io(*io) Currently connected socket     */
        SocketsEnum mLastDisconnection;    /**< *o (--) trick_chkpnt_io(*io) Socket last disconnected from  */
        SocketsEnum mConnectionRequest;    /**<    (--) trick_chkpnt_io(**)  Connect to socket command      */
        SocketsEnum mDisconnectionRequest; /**<    (--) trick_chkpnt_io(**)  Disconnect form socket command */
        /// @brief  Default constructs this jumper plug.
        NetExportBaseNominal_Sockets(const std::string name)
            :
            GunnsFluidJumperPlug(name, static_cast <int> (NONE)),
            mActiveConnection    (NONE),
            mLastDisconnection   (NONE),
            mConnectionRequest   (NONE),
            mDisconnectionRequest(NONE) {}
        /// @brief Default desctructs this jumper plug.
        virtual ~NetExportBaseNominal_Sockets() {}
        /// @brief Sets the active connection of this plug to the given socket index.
        /// @param[in] index (--) Index to the socket list enumeration.
        virtual void setActiveConnection    (const int index) {mActiveConnection     = static_cast <SocketsEnum> (index);}
        /// @brief Sets the last disconnected socket of this plug to the given socket index.
        /// @param[in] index (--) Index to the socket list enumeration.
        virtual void setLastDisconnection   (const int index) {mLastDisconnection    = static_cast <SocketsEnum> (index);}
        /// @brief Sets the command to connected to the given socket index.
        /// @param[in] index (--) Index to the socket list enumeration.
        virtual void setConnectionRequest   (const int index) {mConnectionRequest    = static_cast <SocketsEnum> (index);}
        /// @brief Sets the command to disconnect to the given socket index.
        /// @param[in] index (--) Index to the socket list enumeration.
        virtual void setDisconnectionRequest(const int index) {mDisconnectionRequest = static_cast <SocketsEnum> (index);}
        /// @brief Returns the index of the currently connected socket.
        /// @return int (--) Index to the socket list enumeration.
        virtual int  getActiveConnection()     {return static_cast <int> (mActiveConnection);}
        /// @brief Returns the index of the socket last disconnected from.
        /// @return int (--) Index to the socket list enumeration.
        virtual int  getLastDisconnection()    {return static_cast <int> (mLastDisconnection);}
        /// @brief Returns the index of the socket the plug is commanded to connect to.
        /// @return int (--) Index to the socket list enumeration.
        virtual int  getConnectionRequest()    {return static_cast <int> (mConnectionRequest);}
        /// @brief Returns the index of the socket the plug is commanded to disconnect from.
        /// @return int (--) Index to the socket list enumeration.
        virtual int  getDisconnectionRequest() {return static_cast <int> (mDisconnectionRequest);}
        /// @brief Returns the index of no socket, the last index in the list.
        /// @return int (--) Index to the socket list enumeration.
        virtual int  getNoConnection()         {return static_cast <int> (NONE);}
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportBaseNominal GUNNS Network Config Data
///
/// @details  Configuration data class for the NetExportBaseNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportBaseNominalConfigData
{
    public:
        // Solver configuration data
        GunnsConfigData netSolver;    /**< (--) trick_chkpnt_io(**) Network solver config data. */
        // Spotters configuration data
        ConfigData TestSpotter;    /**< (--) trick_chkpnt_io(**) TestSpotter config data. */
        // Links configuration data
        GunnsBasicSourceConfigData testSource;    /**< (--) trick_chkpnt_io(**) testSource config data. */
        GunnsBasicConductorConfigData testConductor;    /**< (--) trick_chkpnt_io(**) testConductor config data. */
        GunnsBasicPotentialConfigData testPotential;    /**< (--) trick_chkpnt_io(**) testPotential config data. */
        GunnsBasicSocketConfigData GroundSocket;    /**< (--) trick_chkpnt_io(**) GroundSocket config data. */
        GunnsBasicCapacitorConfigData TestCapacitor;    /**< (--) trick_chkpnt_io(**) TestCapacitor config data. */
        GunnsBasicExternalSupplyConfigData textExtSource;    /**< (--) trick_chkpnt_io(**) textExtSource config data. */
        GunnsBasicExternalDemandConfigData testExtDemand;    /**< (--) trick_chkpnt_io(**) testExtDemand config data. */
        GunnsBasicJumperConfigData testJumper;    /**< (--) trick_chkpnt_io(**) testJumper config data. */
        /// @brief  Default constructs this network configuration data.
        NetExportBaseNominalConfigData(const std::string& name, NetExportBaseNominal* network);
        /// @brief  Default destructs this network configuration data.
        virtual ~NetExportBaseNominalConfigData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportBaseNominalConfigData(const NetExportBaseNominalConfigData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportBaseNominalConfigData& operator =(const NetExportBaseNominalConfigData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportBaseNominal GUNNS Network Input Data
///
/// @details  Input data class for the NetExportBaseNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportBaseNominalInputData
{
    public:
        // Spotters input data
        InputData TestSpotter;    /**< (--) trick_chkpnt_io(**) TestSpotter input data. */
        // Links input data
        GunnsBasicSourceInputData testSource;    /**< (--) trick_chkpnt_io(**) testSource input data. */
        GunnsBasicConductorInputData testConductor;    /**< (--) trick_chkpnt_io(**) testConductor input data. */
        GunnsBasicPotentialInputData testPotential;    /**< (--) trick_chkpnt_io(**) testPotential input data. */
        GunnsBasicSocketInputData GroundSocket;    /**< (--) trick_chkpnt_io(**) GroundSocket input data. */
        GunnsBasicCapacitorInputData TestCapacitor;    /**< (--) trick_chkpnt_io(**) TestCapacitor input data. */
        GunnsBasicExternalSupplyInputData textExtSource;    /**< (--) trick_chkpnt_io(**) textExtSource input data. */
        GunnsBasicExternalDemandInputData testExtDemand;    /**< (--) trick_chkpnt_io(**) testExtDemand input data. */
        GunnsBasicJumperInputData testJumper;    /**< (--) trick_chkpnt_io(**) testJumper input data. */
        /// @brief  Default constructs this network input data.
        NetExportBaseNominalInputData(NetExportBaseNominal* network);
        /// @brief  Default destructs this network input data.
        virtual ~NetExportBaseNominalInputData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportBaseNominalInputData(const NetExportBaseNominalInputData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportBaseNominalInputData& operator =(const NetExportBaseNominalInputData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportBaseNominal GUNNS Network
///
/// @details  Main class for the NetExportBaseNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportBaseNominal : public GunnsNetworkBase
{
    TS_MAKE_SIM_COMPATIBLE(NetExportBaseNominal);
    public:
        /// @brief  Enumeration of the NetExportBaseNominal Network nodes.
        enum Nodes
        {
            Node0 = 0,    ///< Node 0
            Node1 = 1,    ///< Node 1
            Node2 = 2,    ///< Node 2
            Node3 = 3,    ///< Node 3
            Node4 = 4,    ///< Node 4
            GROUND = 5,    ///< Ground Node
            N_NODES = 6    ///< Number of nodes including Ground
        };
        // Network declarations
        GunnsBasicNode netNodes[NetExportBaseNominal::N_NODES];    /**< (--) Network nodes array. */
        NetExportBaseNominalConfigData netConfig;    /**< (--) trick_chkpnt_io(**) Network config data. */
        NetExportBaseNominalInputData netInput;    /**< (--) trick_chkpnt_io(**) Network input data. */
        // Data Tables
        static const double DataTableX[1];    /**< (--) DataTable X (x) axis. */
        static const double DataTableY[1];    /**< (--) DataTable Y (y) axis. */
        TsLinearInterpolator DataTable;    /**< (--) DataTable linear interpolator. */
        // Spotters
         TestSpotter;    /**< (--) TestSpotter instance. */
        // Jumper Plugs
        NetExportBaseNominal_Sockets testJumperPlug0; /**< (--) testJumperPlug0 instance. */
        NetExportBaseNominal_Sockets testJumperPlug1; /**< (--) testJumperPlug1 instance. */
        // Links
        GunnsBasicSource testSource;    /**< (--) testSource instance. */
        GunnsBasicConductor testConductor;    /**< (--) testConductor instance. */
        GunnsBasicPotential testPotential;    /**< (--) testPotential instance. */
        GunnsBasicSocket GroundSocket;    /**< (--) GroundSocket instance. */
        GunnsBasicCapacitor TestCapacitor;    /**< (--) TestCapacitor instance. */
        GunnsBasicExternalSupply textExtSource;    /**< (--) textExtSource instance. */
        GunnsBasicExternalDemand testExtDemand;    /**< (--) testExtDemand instance. */
        GunnsBasicJumper testJumper;    /**< (--) testJumper instance. */
        /// @brief  Default constructs this network.
        NetExportBaseNominal(const std::string& name = "");
        /// @brief  Default destructs this network.
        virtual ~NetExportBaseNominal();
        /// @brief  Network nodes initialization task.
        virtual void initNodes(const std::string& name);
        /// @brief  Network links & spotters initialization task.
        virtual void initNetwork();
        /// @brief  Update network spotters before the solver solution.
        virtual void stepSpottersPre(const double timeStep);
        /// @brief  Update network spotters after the solver solution.
        virtual void stepSpottersPost(const double timeStep);

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportBaseNominal(const NetExportBaseNominal&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportBaseNominal& operator =(const NetExportBaseNominal&);
};

/// @}

#endif
