/**
@file  NetExportThermalNominal.cpp
@brief NetExportThermalNominal GUNNS Basic Network implementation.

LIBRARY DEPENDENCY:
(
  (aspects/thermal/GunnsThermalCapacitor.o)
  (aspects/thermal/GunnsThermalHeater.o)
  (aspects/thermal/GunnsThermalMultiPanel.o)
  (aspects/thermal/GunnsThermalPanel.o)
  (aspects/thermal/GunnsThermalPhaseChangeBattery.o)
  (aspects/thermal/GunnsThermalPotential.o)
  (aspects/thermal/GunnsThermalRadiation.o)
  (aspects/thermal/GunnsThermalSource.o)
  (aspects/thermal/GunnsThermoelectricDevice.o)
  (core/network/GunnsNetworkBase.o)
)

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.6.0) (2026-07-16 09:24:03.324736))
*/

#include "NetExportThermalNominal.hh"
#include "simulation/hs/TsHsMsg.hh"
#include "software/exceptions/TsInitializationException.hh"

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name    (--) Name of the network for H&S messages.
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportThermalNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportThermalNominalConfigData::NetExportThermalNominalConfigData(const std::string& name, NetExportThermalNominal* network)
    :
    netSolver(name + ".netSolver", 0.001, 1.0e-8, 1, 1),
    // Spotter Config Data
    // Link Config Data
    Cap0(name + ".Cap0", &network->netNodeList, -1),
    TestSource(name + ".TestSource", &network->netNodeList, 1.0, 0),
    TestRadiation(name + ".TestRadiation", &network->netNodeList, 0.0),
    Cap1(name + ".Cap1", &network->netNodeList, -1),
    TestPotential(name + ".TestPotential", &network->netNodeList, 0.0),
    Cap2(name + ".Cap2", &network->netNodeList, -1),
    TestHeater(name + ".TestHeater", &network->netNodeList, 1.0, 0),
    TestDevice(name + ".TestDevice", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    Cap4(name + ".Cap4", &network->netNodeList, -1),
    TestPhaseBatt(name + ".TestPhaseBatt", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.5),
    TestPanel(name + ".TestPanel", &network->netNodeList, 1.0, 0, 0.5, 1.0),
    TestMultiPanel(name + ".TestMultiPanel", &network->netNodeList, 1.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0)
{
    // Load config data vectors
    {
        const double array[] = 0;
        TestSource.cFluxDistributionFractions.assign(array, array + sizeof(array) / sizeof(double));
    }
    {
        const double array[] = 0;
        TestHeater.cFluxDistributionFractions.assign(array, array + sizeof(array) / sizeof(double));
    }
    {
        const double array[] = 0;
        TestPanel.cFluxDistributionFractions.assign(array, array + sizeof(array) / sizeof(double));
    }
    {
        const double array[] = 0;
        TestMultiPanel.cFluxDistributionFractions.assign(array, array + sizeof(array) / sizeof(double));
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportThermalNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportThermalNominalConfigData::~NetExportThermalNominalConfigData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportThermalNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportThermalNominalInputData::NetExportThermalNominalInputData(NetExportThermalNominal* network)
    :
    // Spotter Input Data
    // Link Input Data
    Cap0(false, 0.0, 0.1, DEFAULT_TEMPERATURE, false, DEFAULT_TEMPERATURE),
    TestSource(false, 0.0, 0.0, false, 0.0),
    TestRadiation(false, 0.0, 1.0),
    Cap1(false, 0.0, 0.1, DEFAULT_TEMPERATURE, false, DEFAULT_TEMPERATURE),
    TestPotential(false, 0.0, 0.0),
    Cap2(false, 0.0, 0.1, DEFAULT_TEMPERATURE, false, DEFAULT_TEMPERATURE),
    TestHeater(false, 0.0, 0.0, false, 0.0),
    TestDevice(false, 0.0, false, 0.0),
    Cap4(false, 0.0, 0.1, DEFAULT_TEMPERATURE, false, DEFAULT_TEMPERATURE),
    TestPhaseBatt(0.0, 0.0, 0.0, false, 0.0),
    TestPanel(false, 0.0, 0.0, false, 0.0),
    TestMultiPanel(false, 0.0, 0.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
{
    // Load input data vectors
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportThermalNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportThermalNominalInputData::~NetExportThermalNominalInputData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Default constructs the NetExportThermalNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportThermalNominal::NetExportThermalNominal(const std::string& name)
    :
    GunnsNetworkBase(name, N_NODES, netNodes),
    netNodes(),
    netConfig(name, this),
    netInput(this),
    // Data Tables
    // Spotters
    // Links
    Cap0(),
    TestSource(),
    TestRadiation(),
    Cap1(),
    TestPotential(),
    Cap2(),
    TestHeater(),
    TestDevice(),
    Cap4(),
    TestPhaseBatt(),
    TestPanel(),
    TestMultiPanel()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details Default destructs the NetExportThermalNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportThermalNominal::~NetExportThermalNominal()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Initializes the nodes with their config and input data objects.  The nodes are
///           initialized through the node list object, which may point to this network's nodes
///           (when this is a standalone network), or the super-network's nodes (as a sub-network).
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportThermalNominal::initNodes(const std::string& name)
{
    /// - Initialize the nodes.
    netNodeList.mNodes[0 + netSuperNodesOffset].initialize(name + createNodeName(0 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[1 + netSuperNodesOffset].initialize(name + createNodeName(1 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[2 + netSuperNodesOffset].initialize(name + createNodeName(2 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[3 + netSuperNodesOffset].initialize(name + createNodeName(3 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[4 + netSuperNodesOffset].initialize(name + createNodeName(4 + netSuperNodesOffset), 0.0);
    /// - Only init the Ground node if this is not a sub-network.
    if (!netIsSubNetwork) {
        netNodeList.mNodes[5].initialize(name + ".GROUND");
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Initializes this network's links, spotters and solver with their config and input data
///           objects.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportThermalNominal::initNetwork()
{
    const int groundOffset = netNodeList.mNumNodes - N_NODES;

    /// - Register sockets with the jumper plugs.

    /// - Initialize the links.
    netLinks.clear();
    Cap0.initialize(netConfig.Cap0, netInput.Cap0, netLinks, Node0 + netSuperNodesOffset, GROUND + groundOffset);
    {
        const int array[] = {Node0 + netSuperNodesOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        TestSource.initialize(netConfig.TestSource, netInput.TestSource, netLinks, &vector);
    }
    TestRadiation.initialize(netConfig.TestRadiation, netInput.TestRadiation, netLinks, Node0 + netSuperNodesOffset, Node1 + netSuperNodesOffset);
    Cap1.initialize(netConfig.Cap1, netInput.Cap1, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    TestPotential.initialize(netConfig.TestPotential, netInput.TestPotential, netLinks, GROUND + groundOffset, Node2 + netSuperNodesOffset);
    Cap2.initialize(netConfig.Cap2, netInput.Cap2, netLinks, Node2 + netSuperNodesOffset, GROUND + groundOffset);
    {
        const int array[] = {Node2 + netSuperNodesOffset, Node3 + netSuperNodesOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        TestHeater.initialize(netConfig.TestHeater, netInput.TestHeater, netLinks, &vector);
    }
    TestDevice.initialize(netConfig.TestDevice, netInput.TestDevice, netLinks, Node1 + netSuperNodesOffset, Node4 + netSuperNodesOffset);
    Cap4.initialize(netConfig.Cap4, netInput.Cap4, netLinks, Node4 + netSuperNodesOffset, GROUND + groundOffset);
    TestPhaseBatt.initialize(netConfig.TestPhaseBatt, netInput.TestPhaseBatt, netLinks, Node3 + netSuperNodesOffset);
    {
        const int array[] = {Node3 + netSuperNodesOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        TestPanel.initialize(netConfig.TestPanel, netInput.TestPanel, netLinks, &vector);
    }
    {
        const int array[] = {Node4 + netSuperNodesOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        TestMultiPanel.initialize(netConfig.TestMultiPanel, netInput.TestMultiPanel, netLinks, &vector);
    }

    /// - Initialize the spotters.

    /// - Initialize the solver, only if this is not a sub-network.
    if (!netIsSubNetwork) {
        netSolver.initializeNodes(netNodeList);
        netSolver.initialize(netConfig.netSolver, netLinks);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters before solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportThermalNominal::stepSpottersPre(const double timeStep)
{
    /// - Step network spotters prior to solver step.
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in]   timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters after solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportThermalNominal::stepSpottersPost(const double timeStep)
{
    /// - Step network spotters after solver step.
}
