#ifndef NetExportFluidNominal_EXISTS
#define NetExportFluidNominal_EXISTS

/**
@file  NetExportFluidNominal.hh
@brief NetExportFluidNominal GUNNS Fluid Network declarations.


@details
PURPOSE: (Provides classes for the NetExportFluidNominal GUNNS Fluid Network.)

REFERENCES:
  ()

ASSUMPTIONS AND LIMITATIONS:
  ()

LIBRARY DEPENDENCY:
  ((NetExportFluidNominal.o))

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.5.0) (2025-11-19 09:14:34.971019))

@{
*/

#include "software/SimCompatibility/TsSimCompatibility.hh"
#include "core/network/GunnsNetworkBase.hh"
#include "aspects/fluid/capacitor/GunnsFluidAccum.hh"
#include "aspects/fluid/capacitor/GunnsFluidAccumGas.hh"
#include "aspects/fluid/capacitor/GunnsFluidTank.hh"
#include "aspects/fluid/conductor/GunnsFluid3WayCheckValve.hh"
#include "aspects/fluid/conductor/GunnsFluid3WayValve.hh"
#include "aspects/fluid/conductor/GunnsFluidCheckValve.hh"
#include "aspects/fluid/conductor/GunnsFluidLeak.hh"
#include "aspects/fluid/conductor/GunnsFluidValve.hh"
#include "aspects/fluid/potential/GunnsGasFan.hh"
#include "aspects/fluid/potential/GunnsLiquidCentrifugalPump.hh"
#include "aspects/fluid/source/GunnsFluidEvaporation.hh"
#include "aspects/fluid/source/GunnsGasDisplacementPump.hh"
#include "aspects/fluid/source/GunnsLiquidDisplacementPump.hh"
#include "core/GunnsFluidCapacitor.hh"
#include "core/GunnsFluidConductor.hh"
#include "core/GunnsFluidPotential.hh"
#include "core/GunnsFluidSource.hh"

// Forward-declare the main network class for use in the config data.
class NetExportFluidNominal;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief  Data structure for NetExportFluidNominal GUNNS network mass fractions.
////////////////////////////////////////////////////////////////////////////////////////////////////
typedef struct NetExportFluidNominalFractions {
    double GUNNS_O2;
    double GUNNS_N2;
    double GUNNS_H2O;
    double GUNNS_CO2;
} NetExportFluidNominalFractions;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief  Union for NetExportFluidNominal GUNNS network mass fractions as scalars and as an array.
///         The array is used as an argument in the PolyFluidInputData constructor.
////////////////////////////////////////////////////////////////////////////////////////////////////
union NetExportFluidNominalMassFractions {
    NetExportFluidNominalFractions scalar;
    double array[sizeof(NetExportFluidNominalFractions)/sizeof(double)];
    NetExportFluidNominalMassFractions(
        const double iGUNNS_O2,
        const double iGUNNS_N2,
        const double iGUNNS_H2O,
        const double iGUNNS_CO2);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportFluidNominal GUNNS Network Config Data
///
/// @details  Configuration data class for the NetExportFluidNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportFluidNominalConfigData
{
    public:
        /// @brief  Enumeration of the number of internal constituent fluids in this network.
        enum {N_INTERNAL_FLUIDS = 4};
        // Network fluid configurations
        static FluidProperties::FluidType netInternalFluidTypes[NetExportFluidNominalConfigData::N_INTERNAL_FLUIDS];    /**< (--) trick_chkpnt_io(**) Network internal fluid types array. */
        // Solver configuration data
        GunnsConfigData netSolver;    /**< (--) trick_chkpnt_io(**) Network solver config data. */
        // Spotters configuration data
        // Links configuration data
        GunnsFluidCapacitorConfigData vol0;    /**< (--) trick_chkpnt_io(**) vol0 config data. */
        GunnsFluidPotentialConfigData TestPotential;    /**< (--) trick_chkpnt_io(**) TestPotential config data. */
        GunnsFluidSourceConfigData TestSource;    /**< (--) trick_chkpnt_io(**) TestSource config data. */
        GunnsFluidCapacitorConfigData vol1;    /**< (--) trick_chkpnt_io(**) vol1 config data. */
        GunnsFluidCapacitorConfigData vol2;    /**< (--) trick_chkpnt_io(**) vol2 config data. */
        GunnsFluidValveConfigData TestValue;    /**< (--) trick_chkpnt_io(**) TestValue config data. */
        GunnsFluidTankConfigData TestTank;    /**< (--) trick_chkpnt_io(**) TestTank config data. */
        GunnsFluidCheckValveConfigData TestCheckValve;    /**< (--) trick_chkpnt_io(**) TestCheckValve config data. */
        GunnsFluid3WayValveConfigData Test3WayValve;    /**< (--) trick_chkpnt_io(**) Test3WayValve config data. */
        GunnsGasDisplacementPumpConfigData TestGasPump;    /**< (--) trick_chkpnt_io(**) TestGasPump config data. */
        GunnsGasFanConfigData TestFan;    /**< (--) trick_chkpnt_io(**) TestFan config data. */
        GunnsFluidLeakConfigData TestLeak;    /**< (--) trick_chkpnt_io(**) TestLeak config data. */
        GunnsFluidCapacitorConfigData vol5;    /**< (--) trick_chkpnt_io(**) vol5 config data. */
        GunnsFluidCapacitorConfigData vol4;    /**< (--) trick_chkpnt_io(**) vol4 config data. */
        GunnsFluidCapacitorConfigData vol6;    /**< (--) trick_chkpnt_io(**) vol6 config data. */
        GunnsFluidCapacitorConfigData vol7;    /**< (--) trick_chkpnt_io(**) vol7 config data. */
        GunnsFluidCapacitorConfigData vol8;    /**< (--) trick_chkpnt_io(**) vol8 config data. */
        GunnsFluidCapacitorConfigData vol10;    /**< (--) trick_chkpnt_io(**) vol10 config data. */
        GunnsFluidSourceConfigData TestSource2;    /**< (--) trick_chkpnt_io(**) TestSource2 config data. */
        GunnsFluidAccumGasConfigData TestGasAccum;    /**< (--) trick_chkpnt_io(**) TestGasAccum config data. */
        GunnsFluid3WayCheckValveConfigData 3WayCheckValue;    /**< (--) trick_chkpnt_io(**) 3WayCheckValue config data. */
        GunnsGasFanConfigData testGasFan;    /**< (--) trick_chkpnt_io(**) testGasFan config data. */
        GunnsFluidCapacitorConfigData vol9;    /**< (--) trick_chkpnt_io(**) vol9 config data. */
        GunnsFluidCapacitorConfigData vol12;    /**< (--) trick_chkpnt_io(**) vol12 config data. */
        GunnsLiquidDisplacementPumpConfigData TestLiquidPump;    /**< (--) trick_chkpnt_io(**) TestLiquidPump config data. */
        GunnsFluidAccumConfigData TestSpringAccum;    /**< (--) trick_chkpnt_io(**) TestSpringAccum config data. */
        GunnsFluidCapacitorConfigData vol14;    /**< (--) trick_chkpnt_io(**) vol14 config data. */
        GunnsFluidConductorConfigData TestConductor;    /**< (--) trick_chkpnt_io(**) TestConductor config data. */
        GunnsFluidCapacitorConfigData vol15;    /**< (--) trick_chkpnt_io(**) vol15 config data. */
        GunnsLiquidCentrifugalPumpConfigData TestLiquidCPump;    /**< (--) trick_chkpnt_io(**) TestLiquidCPump config data. */
        GunnsFluidCapacitorConfigData vol16;    /**< (--) trick_chkpnt_io(**) vol16 config data. */
        GunnsFluidEvaporationConfigData TestLiquidEvaporator;    /**< (--) trick_chkpnt_io(**) TestLiquidEvaporator config data. */
        /// @brief  Default constructs this network configuration data.
        NetExportFluidNominalConfigData(const std::string& name, NetExportFluidNominal* network);
        /// @brief  Default destructs this network configuration data.
        virtual ~NetExportFluidNominalConfigData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportFluidNominalConfigData(const NetExportFluidNominalConfigData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportFluidNominalConfigData& operator =(const NetExportFluidNominalConfigData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportFluidNominal GUNNS Network Input Data
///
/// @details  Input data class for the NetExportFluidNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportFluidNominalInputData
{
    public:
        // Internal network fluids
        NetExportFluidNominalMassFractions FluidStateFractions;    /**< (--) trick_chkpnt_io(**) Fluid mass fractions. */
        PolyFluidInputData FluidState;    /**< (--) trick_chkpnt_io(**) Fluid input data. */
        NetExportFluidNominalMassFractions FluidState2Fractions;    /**< (--) trick_chkpnt_io(**) Fluid mass fractions. */
        PolyFluidInputData FluidState2;    /**< (--) trick_chkpnt_io(**) Fluid input data. */
        // Spotters input data
        // Links input data
        GunnsFluidCapacitorInputData vol0;    /**< (--) trick_chkpnt_io(**) vol0 input data. */
        GunnsFluidPotentialInputData TestPotential;    /**< (--) trick_chkpnt_io(**) TestPotential input data. */
        GunnsFluidSourceInputData TestSource;    /**< (--) trick_chkpnt_io(**) TestSource input data. */
        GunnsFluidCapacitorInputData vol1;    /**< (--) trick_chkpnt_io(**) vol1 input data. */
        GunnsFluidCapacitorInputData vol2;    /**< (--) trick_chkpnt_io(**) vol2 input data. */
        GunnsFluidValveInputData TestValue;    /**< (--) trick_chkpnt_io(**) TestValue input data. */
        GunnsFluidTankInputData TestTank;    /**< (--) trick_chkpnt_io(**) TestTank input data. */
        GunnsFluidCheckValveInputData TestCheckValve;    /**< (--) trick_chkpnt_io(**) TestCheckValve input data. */
        GunnsFluid3WayValveInputData Test3WayValve;    /**< (--) trick_chkpnt_io(**) Test3WayValve input data. */
        GunnsGasDisplacementPumpInputData TestGasPump;    /**< (--) trick_chkpnt_io(**) TestGasPump input data. */
        GunnsGasFanInputData TestFan;    /**< (--) trick_chkpnt_io(**) TestFan input data. */
        GunnsFluidLeakInputData TestLeak;    /**< (--) trick_chkpnt_io(**) TestLeak input data. */
        GunnsFluidCapacitorInputData vol5;    /**< (--) trick_chkpnt_io(**) vol5 input data. */
        GunnsFluidCapacitorInputData vol4;    /**< (--) trick_chkpnt_io(**) vol4 input data. */
        GunnsFluidCapacitorInputData vol6;    /**< (--) trick_chkpnt_io(**) vol6 input data. */
        GunnsFluidCapacitorInputData vol7;    /**< (--) trick_chkpnt_io(**) vol7 input data. */
        GunnsFluidCapacitorInputData vol8;    /**< (--) trick_chkpnt_io(**) vol8 input data. */
        GunnsFluidCapacitorInputData vol10;    /**< (--) trick_chkpnt_io(**) vol10 input data. */
        GunnsFluidSourceInputData TestSource2;    /**< (--) trick_chkpnt_io(**) TestSource2 input data. */
        GunnsFluidAccumGasInputData TestGasAccum;    /**< (--) trick_chkpnt_io(**) TestGasAccum input data. */
        GunnsFluid3WayCheckValveInputData 3WayCheckValue;    /**< (--) trick_chkpnt_io(**) 3WayCheckValue input data. */
        GunnsGasFanInputData testGasFan;    /**< (--) trick_chkpnt_io(**) testGasFan input data. */
        GunnsFluidCapacitorInputData vol9;    /**< (--) trick_chkpnt_io(**) vol9 input data. */
        GunnsFluidCapacitorInputData vol12;    /**< (--) trick_chkpnt_io(**) vol12 input data. */
        GunnsLiquidDisplacementPumpInputData TestLiquidPump;    /**< (--) trick_chkpnt_io(**) TestLiquidPump input data. */
        GunnsFluidAccumInputData TestSpringAccum;    /**< (--) trick_chkpnt_io(**) TestSpringAccum input data. */
        GunnsFluidCapacitorInputData vol14;    /**< (--) trick_chkpnt_io(**) vol14 input data. */
        GunnsFluidConductorInputData TestConductor;    /**< (--) trick_chkpnt_io(**) TestConductor input data. */
        GunnsFluidCapacitorInputData vol15;    /**< (--) trick_chkpnt_io(**) vol15 input data. */
        GunnsLiquidCentrifugalPumpInputData TestLiquidCPump;    /**< (--) trick_chkpnt_io(**) TestLiquidCPump input data. */
        GunnsFluidCapacitorInputData vol16;    /**< (--) trick_chkpnt_io(**) vol16 input data. */
        GunnsFluidEvaporationInputData TestLiquidEvaporator;    /**< (--) trick_chkpnt_io(**) TestLiquidEvaporator input data. */
        /// @brief  Default constructs this network input data.
        NetExportFluidNominalInputData(NetExportFluidNominal* network);
        /// @brief  Default destructs this network input data.
        virtual ~NetExportFluidNominalInputData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportFluidNominalInputData(const NetExportFluidNominalInputData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportFluidNominalInputData& operator =(const NetExportFluidNominalInputData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportFluidNominal GUNNS Network
///
/// @details  Main class for the NetExportFluidNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportFluidNominal : public GunnsNetworkBase
{
    TS_MAKE_SIM_COMPATIBLE(NetExportFluidNominal);
    public:
        /// @brief  Enumeration of the NetExportFluidNominal Network nodes.
        enum Nodes
        {
            Node0 = 0,    ///< Node 0
            Node1 = 1,    ///< Node 1
            Node2 = 2,    ///< Node 2
            Node3 = 3,    ///< Node 3
            Node4 = 4,    ///< Node 4
            Node5 = 5,    ///< Node 5
            Node6 = 6,    ///< Node 6
            Node7 = 7,    ///< Node 7
            Node8 = 8,    ///< Node 8
            Node9 = 9,    ///< Node 9
            Node10 = 10,    ///< Node 10
            Node11 = 11,    ///< Node 11
            Node12 = 12,    ///< Node 12
            Node13 = 13,    ///< Node 13
            Node14 = 14,    ///< Node 14
            Node15 = 15,    ///< Node 15
            Node16 = 16,    ///< Node 16
            GROUND = 17,    ///< Ground Node
            N_NODES = 18    ///< Number of nodes including Ground
        };
        // Network declarations
        GunnsFluidNode netNodes[NetExportFluidNominal::N_NODES];    /**< (--) Network nodes array. */
        NetExportFluidNominalConfigData netConfig;    /**< (--) trick_chkpnt_io(**) Network config data. */
        NetExportFluidNominalInputData netInput;    /**< (--) trick_chkpnt_io(**) Network input data. */
        const DefinedFluidProperties netFluidProperties;        /**< (--) trick_chkpnt_io(**) Network defined fluid properties. */
        PolyFluidConfigData          netInternalFluidConfig;    /**< (--) trick_chkpnt_io(**) Network internal fluid config. */
        // Data Tables
        // Spotters
        // Links
        GunnsFluidCapacitor vol0;    /**< (--) vol0 instance. */
        GunnsFluidPotential TestPotential;    /**< (--) TestPotential instance. */
        GunnsFluidSource TestSource;    /**< (--) TestSource instance. */
        GunnsFluidCapacitor vol1;    /**< (--) vol1 instance. */
        GunnsFluidCapacitor vol2;    /**< (--) vol2 instance. */
        GunnsFluidValve TestValue;    /**< (--) TestValue instance. */
        GunnsFluidTank TestTank;    /**< (--) TestTank instance. */
        GunnsFluidCheckValve TestCheckValve;    /**< (--) TestCheckValve instance. */
        GunnsFluid3WayValve Test3WayValve;    /**< (--) Test3WayValve instance. */
        GunnsGasDisplacementPump TestGasPump;    /**< (--) TestGasPump instance. */
        GunnsGasFan TestFan;    /**< (--) TestFan instance. */
        GunnsFluidLeak TestLeak;    /**< (--) TestLeak instance. */
        GunnsFluidCapacitor vol5;    /**< (--) vol5 instance. */
        GunnsFluidCapacitor vol4;    /**< (--) vol4 instance. */
        GunnsFluidCapacitor vol6;    /**< (--) vol6 instance. */
        GunnsFluidCapacitor vol7;    /**< (--) vol7 instance. */
        GunnsFluidCapacitor vol8;    /**< (--) vol8 instance. */
        GunnsFluidCapacitor vol10;    /**< (--) vol10 instance. */
        GunnsFluidSource TestSource2;    /**< (--) TestSource2 instance. */
        GunnsFluidAccumGas TestGasAccum;    /**< (--) TestGasAccum instance. */
        GunnsFluid3WayCheckValve 3WayCheckValue;    /**< (--) 3WayCheckValue instance. */
        GunnsGasFan testGasFan;    /**< (--) testGasFan instance. */
        GunnsFluidCapacitor vol9;    /**< (--) vol9 instance. */
        GunnsFluidCapacitor vol12;    /**< (--) vol12 instance. */
        GunnsLiquidDisplacementPump TestLiquidPump;    /**< (--) TestLiquidPump instance. */
        GunnsFluidAccum TestSpringAccum;    /**< (--) TestSpringAccum instance. */
        GunnsFluidCapacitor vol14;    /**< (--) vol14 instance. */
        GunnsFluidConductor TestConductor;    /**< (--) TestConductor instance. */
        GunnsFluidCapacitor vol15;    /**< (--) vol15 instance. */
        GunnsLiquidCentrifugalPump TestLiquidCPump;    /**< (--) TestLiquidCPump instance. */
        GunnsFluidCapacitor vol16;    /**< (--) vol16 instance. */
        GunnsFluidEvaporation TestLiquidEvaporator;    /**< (--) TestLiquidEvaporator instance. */
        /// @brief  Default constructs this network.
        NetExportFluidNominal(const std::string& name = "");
        /// @brief  Default destructs this network.
        virtual ~NetExportFluidNominal();
        /// @brief  Network nodes initialization task.
        virtual void initNodes(const std::string& name);
        /// @brief  Network links & spotters initialization task.
        virtual void initNetwork();
        /// @brief  Update network spotters before the solver solution.
        virtual void stepSpottersPre(const double timeStep);
        /// @brief  Update network spotters after the solver solution.
        virtual void stepSpottersPost(const double timeStep);
        /// @brief  Returns this network's fluid configuration.
        virtual const PolyFluidConfigData* getFluidConfig() const;

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportFluidNominal(const NetExportFluidNominal&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportFluidNominal& operator =(const NetExportFluidNominal&);
};

/// @}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @returns  PolyFluidConfigData* (--) Pointer to this network's fluid configuration.
///
/// @details  Returns this network's fluid configuration.
////////////////////////////////////////////////////////////////////////////////////////////////////
inline const PolyFluidConfigData* NetExportFluidNominal::getFluidConfig() const
{
    return &netInternalFluidConfig;
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] iGUNNS_O2 (--) Mass fraction of the GUNNS_O2 constituent in the composite fluid.
/// @param[in] iGUNNS_N2 (--) Mass fraction of the GUNNS_N2 constituent in the composite fluid.
/// @param[in] iGUNNS_H2O (--) Mass fraction of the GUNNS_H2O constituent in the composite fluid.
/// @param[in] iGUNNS_CO2 (--) Mass fraction of the GUNNS_CO2 constituent in the composite fluid.
///
/// @details  Constructs the mass fraction union from the scalar mass fraction arguments.
////////////////////////////////////////////////////////////////////////////////////////////////////
inline NetExportFluidNominalMassFractions::NetExportFluidNominalMassFractions (
    const double iGUNNS_O2,
    const double iGUNNS_N2,
    const double iGUNNS_H2O,
    const double iGUNNS_CO2)
{
    scalar.GUNNS_O2 = iGUNNS_O2;
    scalar.GUNNS_N2 = iGUNNS_N2;
    scalar.GUNNS_H2O = iGUNNS_H2O;
    scalar.GUNNS_CO2 = iGUNNS_CO2;
}

#endif
