#ifndef NetExportThermalNominal_EXISTS
#define NetExportThermalNominal_EXISTS

/**
@file  NetExportThermalNominal.hh
@brief NetExportThermalNominal GUNNS Basic Network declarations.


@details
PURPOSE: (Provides classes for the NetExportThermalNominal GUNNS Basic Network.)

REFERENCES:
  ()

ASSUMPTIONS AND LIMITATIONS:
  ()

LIBRARY DEPENDENCY:
  ((NetExportThermalNominal.o))

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.5.0) (2025-11-19 09:14:34.607010))

@{
*/

#include "software/SimCompatibility/TsSimCompatibility.hh"
#include "core/network/GunnsNetworkBase.hh"
#include "aspects/thermal/GunnsThermalCapacitor.hh"
#include "aspects/thermal/GunnsThermalHeater.hh"
#include "aspects/thermal/GunnsThermalMultiPanel.hh"
#include "aspects/thermal/GunnsThermalPanel.hh"
#include "aspects/thermal/GunnsThermalPhaseChangeBattery.hh"
#include "aspects/thermal/GunnsThermalPotential.hh"
#include "aspects/thermal/GunnsThermalRadiation.hh"
#include "aspects/thermal/GunnsThermalSource.hh"
#include "aspects/thermal/GunnsThermoelectricDevice.hh"

// Forward-declare the main network class for use in the config data.
class NetExportThermalNominal;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportThermalNominal GUNNS Network Config Data
///
/// @details  Configuration data class for the NetExportThermalNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportThermalNominalConfigData
{
    public:
        // Solver configuration data
        GunnsConfigData netSolver;    /**< (--) trick_chkpnt_io(**) Network solver config data. */
        // Spotters configuration data
        // Links configuration data
        GunnsThermalCapacitorConfigData Cap0;    /**< (--) trick_chkpnt_io(**) Cap0 config data. */
        GunnsThermalSourceConfigData TestSource;    /**< (--) trick_chkpnt_io(**) TestSource config data. */
        GunnsThermalRadiationConfigData TestRadiation;    /**< (--) trick_chkpnt_io(**) TestRadiation config data. */
        GunnsThermalCapacitorConfigData Cap1;    /**< (--) trick_chkpnt_io(**) Cap1 config data. */
        GunnsThermalPotentialConfigData TestPotential;    /**< (--) trick_chkpnt_io(**) TestPotential config data. */
        GunnsThermalCapacitorConfigData Cap2;    /**< (--) trick_chkpnt_io(**) Cap2 config data. */
        GunnsThermalHeaterConfigData TestHeater;    /**< (--) trick_chkpnt_io(**) TestHeater config data. */
        GunnsThermoelectricDeviceConfigData TestDevice;    /**< (--) trick_chkpnt_io(**) TestDevice config data. */
        GunnsThermalCapacitorConfigData Cap4;    /**< (--) trick_chkpnt_io(**) Cap4 config data. */
        GunnsThermalPhaseChangeBatteryConfigData TestPhaseBatt;    /**< (--) trick_chkpnt_io(**) TestPhaseBatt config data. */
        GunnsThermalPanelConfigData TestPanel;    /**< (--) trick_chkpnt_io(**) TestPanel config data. */
        GunnsThermalMultiPanelConfigData TestMultiPanel;    /**< (--) trick_chkpnt_io(**) TestMultiPanel config data. */
        /// @brief  Default constructs this network configuration data.
        NetExportThermalNominalConfigData(const std::string& name, NetExportThermalNominal* network);
        /// @brief  Default destructs this network configuration data.
        virtual ~NetExportThermalNominalConfigData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportThermalNominalConfigData(const NetExportThermalNominalConfigData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportThermalNominalConfigData& operator =(const NetExportThermalNominalConfigData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportThermalNominal GUNNS Network Input Data
///
/// @details  Input data class for the NetExportThermalNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportThermalNominalInputData
{
    public:
        // Spotters input data
        // Links input data
        GunnsThermalCapacitorInputData Cap0;    /**< (--) trick_chkpnt_io(**) Cap0 input data. */
        GunnsThermalSourceInputData TestSource;    /**< (--) trick_chkpnt_io(**) TestSource input data. */
        GunnsThermalRadiationInputData TestRadiation;    /**< (--) trick_chkpnt_io(**) TestRadiation input data. */
        GunnsThermalCapacitorInputData Cap1;    /**< (--) trick_chkpnt_io(**) Cap1 input data. */
        GunnsThermalPotentialInputData TestPotential;    /**< (--) trick_chkpnt_io(**) TestPotential input data. */
        GunnsThermalCapacitorInputData Cap2;    /**< (--) trick_chkpnt_io(**) Cap2 input data. */
        GunnsThermalHeaterInputData TestHeater;    /**< (--) trick_chkpnt_io(**) TestHeater input data. */
        GunnsThermoelectricDeviceInputData TestDevice;    /**< (--) trick_chkpnt_io(**) TestDevice input data. */
        GunnsThermalCapacitorInputData Cap4;    /**< (--) trick_chkpnt_io(**) Cap4 input data. */
        GunnsThermalPhaseChangeBatteryInputData TestPhaseBatt;    /**< (--) trick_chkpnt_io(**) TestPhaseBatt input data. */
        GunnsThermalPanelInputData TestPanel;    /**< (--) trick_chkpnt_io(**) TestPanel input data. */
        GunnsThermalMultiPanelInputData TestMultiPanel;    /**< (--) trick_chkpnt_io(**) TestMultiPanel input data. */
        /// @brief  Default constructs this network input data.
        NetExportThermalNominalInputData(NetExportThermalNominal* network);
        /// @brief  Default destructs this network input data.
        virtual ~NetExportThermalNominalInputData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportThermalNominalInputData(const NetExportThermalNominalInputData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportThermalNominalInputData& operator =(const NetExportThermalNominalInputData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportThermalNominal GUNNS Network
///
/// @details  Main class for the NetExportThermalNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportThermalNominal : public GunnsNetworkBase
{
    TS_MAKE_SIM_COMPATIBLE(NetExportThermalNominal);
    public:
        /// @brief  Enumeration of the NetExportThermalNominal Network nodes.
        enum Nodes
        {
            Node0 = 0,    ///< Node 0
            Node1 = 1,    ///< Node 1
            Node2 = 2,    ///< Node 2
            Node3 = 3,    ///< Node 3
            Node4 = 4,    ///< Node 4
            GROUND = 5,    ///< Ground Node
            N_NODES = 6    ///< Number of nodes including Ground
        };
        // Network declarations
        GunnsBasicNode netNodes[NetExportThermalNominal::N_NODES];    /**< (--) Network nodes array. */
        NetExportThermalNominalConfigData netConfig;    /**< (--) trick_chkpnt_io(**) Network config data. */
        NetExportThermalNominalInputData netInput;    /**< (--) trick_chkpnt_io(**) Network input data. */
        // Data Tables
        // Spotters
        // Links
        GunnsThermalCapacitor Cap0;    /**< (--) Cap0 instance. */
        GunnsThermalSource TestSource;    /**< (--) TestSource instance. */
        GunnsThermalRadiation TestRadiation;    /**< (--) TestRadiation instance. */
        GunnsThermalCapacitor Cap1;    /**< (--) Cap1 instance. */
        GunnsThermalPotential TestPotential;    /**< (--) TestPotential instance. */
        GunnsThermalCapacitor Cap2;    /**< (--) Cap2 instance. */
        GunnsThermalHeater TestHeater;    /**< (--) TestHeater instance. */
        GunnsThermoelectricDevice TestDevice;    /**< (--) TestDevice instance. */
        GunnsThermalCapacitor Cap4;    /**< (--) Cap4 instance. */
        GunnsThermalPhaseChangeBattery TestPhaseBatt;    /**< (--) TestPhaseBatt instance. */
        GunnsThermalPanel TestPanel;    /**< (--) TestPanel instance. */
        GunnsThermalMultiPanel TestMultiPanel;    /**< (--) TestMultiPanel instance. */
        /// @brief  Default constructs this network.
        NetExportThermalNominal(const std::string& name = "");
        /// @brief  Default destructs this network.
        virtual ~NetExportThermalNominal();
        /// @brief  Network nodes initialization task.
        virtual void initNodes(const std::string& name);
        /// @brief  Network links & spotters initialization task.
        virtual void initNetwork();
        /// @brief  Update network spotters before the solver solution.
        virtual void stepSpottersPre(const double timeStep);
        /// @brief  Update network spotters after the solver solution.
        virtual void stepSpottersPost(const double timeStep);

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportThermalNominal(const NetExportThermalNominal&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportThermalNominal& operator =(const NetExportThermalNominal&);
};

/// @}

#endif
