/**
@file  NetExportPowerNominal.cpp
@brief NetExportPowerNominal GUNNS Basic Network implementation.

LIBRARY DEPENDENCY:
(
  (aspects/electrical/Batt/GunnsElectBattery.o)
  (aspects/electrical/ConstantPowerLoad/EpsConstantPowerLoad.o)
  (aspects/electrical/Converter/GunnsElectConverterInput.o)
  (aspects/electrical/Converter/GunnsElectConverterOutput.o)
  (aspects/electrical/Diode/GunnsElectRealDiode.o)
  (aspects/electrical/SolarArray/GunnsElectPvArray.o)
  (aspects/electrical/SolarArray/GunnsElectPvRegConv.o)
  (aspects/electrical/SolarArray/GunnsElectPvRegShunt.o)
  (aspects/electrical/Switch/GunnsElectSelector.o)
  (aspects/electrical/Switch/GunnsElectUserLoadSwitch2.o)
  (aspects/electrical/Switch/SwitchElect.o)
  (aspects/electrical/resistive/GunnsElectShort.o)
  (aspects/electrical/resistive/GunnsElectricalResistor.o)
  (aspects/electrical/resistive/GunnsResistiveLoad.o)
  (aspects/electrical/resistive/GunnsResistorPowerFunction.o)
  (core/GunnsBasicFlowController.o)
  (core/network/GunnsNetworkBase.o)
)

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.5.0) (2025-11-19 09:14:34.773649))
*/

#include "NetExportPowerNominal.hh"
#include "simulation/hs/TsHsMsg.hh"
#include "software/exceptions/TsInitializationException.hh"

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name    (--) Name of the network for H&S messages.
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportPowerNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportPowerNominalConfigData::NetExportPowerNominalConfigData(const std::string& name, NetExportPowerNominal* network)
    :
    netSolver(name + ".netSolver", 0.001, 1.0e-8, 1, 1),
    // Spotter Config Data
    // Link Config Data
    TestBatt1(name + ".TestBatt1", &network->netNodeList, 0, false, 0.0, 0.0, 0.0, 0),
    TestBatt2(name + ".TestBatt2", &network->netNodeList, 0, false, 0.0, 0.0, 0.0, 0),
    TestUserLoad(name + ".TestUserLoad", &network->netNodeList, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    TestSwitch(name + ".TestSwitch", &network->netNodeList, 0),
    TestCondIn(name + ".TestCondIn", &network->netNodeList, 0, 0, 0, 0.0, 0.0, 0),
    TestCondOut(name + ".TestCondOut", &network->netNodeList, GunnsElectConverterOutput::VOLTAGE, 0.0, 0.0, 0, 0, 0, 0.0, 0.0, 0, false, 0.0),
    TestSolar1(name + ".TestSolar1", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, false, 0.0, 0.0, 0.0, 0, 0, 0, 0),
    TestShunt(name + ".TestShunt", &network->netNodeList, 0.0, 0.0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
    TestSolar2(name + ".TestSolar2", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, false, 0.0, 0.0, 0.0, 0, 0, 0, 0),
    TestConverter(name + ".TestConverter", &network->netNodeList, 0.0, 0.0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
    TestDiode(name + ".TestDiode", &network->netNodeList, 0.0, 0.0, 0.0),
    TestPowerLoad(name + ".TestPowerLoad", &network->netNodeList, 0.0, 0.0, 0.0),
    TestCurrentLoad(name + ".TestCurrentLoad", &network->netNodeList, 0.0, false, false),
    TestResistor(name + ".TestResistor", &network->netNodeList, 0.0, 0.0),
    TestResistiveLoad(name + ".TestResistiveLoad", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
    TestPowerFunction(name + ".TestPowerFunction", &network->netNodeList, 0.0, 0.0, false),
    TestSwitch1(name + ".TestSwitch1", &network->netNodeList, 0.0, 0),
    TestSwitch2(name + ".TestSwitch2", &network->netNodeList, 0.0, 0),
    TestShort(name + ".TestShort", &network->netNodeList)
{
    // Load config data vectors
    {
        const std::string array[] = {"Battery", "Short", "Node"};
        TestSwitch1.mPortLabels.assign(array, array + sizeof(array) / sizeof(std::string));
    }
    {
        const std::string array[] = {"Battery", "Node", "Short"};
        TestSwitch2.mPortLabels.assign(array, array + sizeof(array) / sizeof(std::string));
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportPowerNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportPowerNominalConfigData::~NetExportPowerNominalConfigData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportPowerNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportPowerNominalInputData::NetExportPowerNominalInputData(NetExportPowerNominal* network)
    :
    // Spotter Input Data
    // Link Input Data
    TestBatt1(false, 0.0, 0.0, false, 0.0, 0.0),
    TestBatt2(false, 0.0, 0.0, false, 0.0, 0.0),
    TestUserLoad(false, 0.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, false, 0.0),
    TestSwitch(false, 0.0, 0),
    TestCondIn(false, 0.0, false, 0.0, 0.0, 0.0),
    TestCondOut(false, 0.0, false, 0.0, 0.0, 0.0),
    TestSolar1(0.0, 0.0, 0.0, 0.0),
    TestShunt(0.0, false, false, 0.0),
    TestSolar2(0.0, 0.0, 0.0, 0.0),
    TestConverter(0.0, 0.0, false, false),
    TestDiode(false, 0.0, false),
    TestPowerLoad(false, 0.0),
    TestCurrentLoad(false, 0.0, false, 0.0, 0.0),
    TestResistor(false, 0.0),
    TestResistiveLoad(false, 0.0, true),
    TestPowerFunction(false, 0.0),
    TestSwitch1(false, 0.0, 0),
    TestSwitch2(false, 0.0, 0),
    TestShort(false, 0.0, 0.0, false, 0.0, false, 0.0, false, 0.0, false, 0.0, false, 0.0)
{
    // Load input data vectors
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportPowerNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportPowerNominalInputData::~NetExportPowerNominalInputData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Default constructs the NetExportPowerNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportPowerNominal::NetExportPowerNominal(const std::string& name)
    :
    GunnsNetworkBase(name, N_NODES, netNodes),
    netNodes(),
    netConfig(name, this),
    netInput(this),
    // Data Tables
    // Spotters
    // Links
    TestBatt1(),
    TestBatt2(),
    TestUserLoad(),
    TestSwitch(),
    TestCondIn(),
    TestCondOut(),
    TestSolar1(),
    TestShunt(),
    TestSolar2(),
    TestConverter(),
    TestDiode(),
    TestPowerLoad(),
    TestCurrentLoad(),
    TestResistor(),
    TestResistiveLoad(),
    TestPowerFunction(),
    TestSwitch1(),
    TestSwitch2(),
    TestShort()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details Default destructs the NetExportPowerNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportPowerNominal::~NetExportPowerNominal()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Initializes the nodes with their config and input data objects.  The nodes are
///           initialized through the node list object, which may point to this network's nodes
///           (when this is a standalone network), or the super-network's nodes (as a sub-network).
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportPowerNominal::initNodes(const std::string& name)
{
    /// - Initialize the nodes.
    netNodeList.mNodes[0 + netSuperNodesOffset].initialize(name + createNodeName(0 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[1 + netSuperNodesOffset].initialize(name + createNodeName(1 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[2 + netSuperNodesOffset].initialize(name + createNodeName(2 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[3 + netSuperNodesOffset].initialize(name + createNodeName(3 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[4 + netSuperNodesOffset].initialize(name + createNodeName(4 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[5 + netSuperNodesOffset].initialize(name + createNodeName(5 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[6 + netSuperNodesOffset].initialize(name + createNodeName(6 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[7 + netSuperNodesOffset].initialize(name + createNodeName(7 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[8 + netSuperNodesOffset].initialize(name + createNodeName(8 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[9 + netSuperNodesOffset].initialize(name + createNodeName(9 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[10 + netSuperNodesOffset].initialize(name + createNodeName(10 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[11 + netSuperNodesOffset].initialize(name + createNodeName(11 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[12 + netSuperNodesOffset].initialize(name + createNodeName(12 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[13 + netSuperNodesOffset].initialize(name + createNodeName(13 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[14 + netSuperNodesOffset].initialize(name + createNodeName(14 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[15 + netSuperNodesOffset].initialize(name + createNodeName(15 + netSuperNodesOffset), 0.0);
    /// - Only init the Ground node if this is not a sub-network.
    if (!netIsSubNetwork) {
        netNodeList.mNodes[16].initialize(name + ".GROUND");
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Initializes this network's links, spotters and solver with their config and input data
///           objects.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportPowerNominal::initNetwork()
{
    const int groundOffset = netNodeList.mNumNodes - N_NODES;

    /// - Register sockets with the jumper plugs.

    /// - Initialize the links.
    netLinks.clear();
    TestBatt1.initialize(netConfig.TestBatt1, netInput.TestBatt1, netLinks, GROUND + groundOffset, Node0 + netSuperNodesOffset);
    TestBatt2.initialize(netConfig.TestBatt2, netInput.TestBatt2, netLinks, GROUND + groundOffset, Node1 + netSuperNodesOffset);
    TestUserLoad.initialize(netConfig.TestUserLoad, netInput.TestUserLoad, netLinks, Node0 + netSuperNodesOffset, Node3 + netSuperNodesOffset);
    TestSwitch.initialize(netConfig.TestSwitch, netInput.TestSwitch, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    TestCondIn.initialize(netConfig.TestCondIn, netInput.TestCondIn, netLinks, Node2 + netSuperNodesOffset);
    TestCondOut.initialize(netConfig.TestCondOut, netInput.TestCondOut, netLinks, Node7 + netSuperNodesOffset);
    TestSolar1.initialize(netConfig.TestSolar1, netInput.TestSolar1, netLinks, Node4 + netSuperNodesOffset);
    TestShunt.initialize(netConfig.TestShunt, netInput.TestShunt, netLinks, Node4 + netSuperNodesOffset, Node5 + netSuperNodesOffset);
    TestSolar2.initialize(netConfig.TestSolar2, netInput.TestSolar2, netLinks, Node6 + netSuperNodesOffset);
    TestConverter.initialize(netConfig.TestConverter, netInput.TestConverter, netLinks, Node6 + netSuperNodesOffset, Node1 + netSuperNodesOffset);
    TestDiode.initialize(netConfig.TestDiode, netInput.TestDiode, netLinks, Node5 + netSuperNodesOffset, Node0 + netSuperNodesOffset);
    TestPowerLoad.initialize(netConfig.TestPowerLoad, netInput.TestPowerLoad, netLinks, Node3 + netSuperNodesOffset, Node8 + netSuperNodesOffset);
    TestCurrentLoad.initialize(netConfig.TestCurrentLoad, netInput.TestCurrentLoad, netLinks, Node7 + netSuperNodesOffset, Node10 + netSuperNodesOffset);
    TestResistor.initialize(netConfig.TestResistor, netInput.TestResistor, netLinks, Node8 + netSuperNodesOffset, Node9 + netSuperNodesOffset);
    TestResistiveLoad.initialize(netConfig.TestResistiveLoad, netInput.TestResistiveLoad, netLinks, Node9 + netSuperNodesOffset, Node11 + netSuperNodesOffset);
    TestPowerFunction.initialize(netConfig.TestPowerFunction, netInput.TestPowerFunction, netLinks, Node10 + netSuperNodesOffset, Node12 + netSuperNodesOffset);
    {
        const int array[] = {Node11 + netSuperNodesOffset, Node13 + netSuperNodesOffset, Node14 + netSuperNodesOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        TestSwitch1.initialize(netConfig.TestSwitch1, netInput.TestSwitch1, netLinks, &vector);
    }
    {
        const int array[] = {Node12 + netSuperNodesOffset, Node14 + netSuperNodesOffset, Node13 + netSuperNodesOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        TestSwitch2.initialize(netConfig.TestSwitch2, netInput.TestSwitch2, netLinks, &vector);
    }
    TestShort.initialize(netConfig.TestShort, netInput.TestShort, netLinks, Node13 + netSuperNodesOffset, Node15 + netSuperNodesOffset);

    /// - Initialize the spotters.

    /// - Initialize the solver, only if this is not a sub-network.
    if (!netIsSubNetwork) {
        netSolver.initializeNodes(netNodeList);
        netSolver.initialize(netConfig.netSolver, netLinks);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters before solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportPowerNominal::stepSpottersPre(const double timeStep)
{
    /// - Step network spotters prior to solver step.
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in]   timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters after solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportPowerNominal::stepSpottersPost(const double timeStep)
{
    /// - Step network spotters after solver step.
}
