/**
@file  NetExportBaseNominal.cpp
@brief NetExportBaseNominal GUNNS Basic Network implementation.

LIBRARY DEPENDENCY:
(
  (.o)
  (core/GunnsBasicCapacitor.o)
  (core/GunnsBasicConductor.o)
  (core/GunnsBasicExternalDemand.o)
  (core/GunnsBasicExternalSupply.o)
  (core/GunnsBasicJumper.o)
  (core/GunnsBasicPotential.o)
  (core/GunnsBasicSocket.o)
  (core/GunnsBasicSource.o)
  (core/GunnsBasicJumperPlug.o)
  (core/network/GunnsNetworkBase.o)
)

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.6.0) (2026-07-16 09:23:02.976195))
*/

#include "NetExportBaseNominal.hh"
#include "simulation/hs/TsHsMsg.hh"
#include "software/exceptions/TsInitializationException.hh"

// Tables data
const double NetExportBaseNominal::DataTableX[1] = {5.0};
const double NetExportBaseNominal::DataTableY[1] = {2.1};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name    (--) Name of the network for H&S messages.
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportBaseNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportBaseNominalConfigData::NetExportBaseNominalConfigData(const std::string& name, NetExportBaseNominal* network)
    :
    netSolver(name + ".netSolver", 0.001, 1.0e-8, 1, 1),
    // Spotter Config Data
    TestSpotter(name + ".TestSpotter"),
    // Link Config Data
    testSource(name + ".testSource", &network->netNodeList),
    testConductor(name + ".testConductor", &network->netNodeList, 0.0),
    testPotential(name + ".testPotential", &network->netNodeList, 0.0),
    GroundSocket(name + ".GroundSocket", &network->netNodeList, 0.0, false),
    TestCapacitor(name + ".TestCapacitor", &network->netNodeList),
    textExtSource(name + ".textExtSource", &network->netNodeList),
    testExtDemand(name + ".testExtDemand", &network->netNodeList, 0.0, 1.0, 1.0e-8, 0.05),
    testJumper(name + ".testJumper", &network->netNodeList, 0.0, &network->testJumperPlug0, &network->testJumperPlug1, True, True)
{
    // Load config data vectors
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportBaseNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportBaseNominalConfigData::~NetExportBaseNominalConfigData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportBaseNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportBaseNominalInputData::NetExportBaseNominalInputData(NetExportBaseNominal* network)
    :
    // Spotter Input Data
    TestSpotter(),
    // Link Input Data
    testSource(false, 0.0, 0.0),
    testConductor(false, 0.0),
    testPotential(false, 0.0, 0.0),
    GroundSocket(false, 0.0),
    TestCapacitor(false, 0.0, 0.0, 0.0),
    textExtSource(false, 0.0, 0.0),
    testExtDemand(false, 0.0, 0.0),
    testJumper(false, 0.0, netExportTest_Sockets::None, netExportTest_Sockets::None)
{
    // Load input data vectors
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportBaseNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportBaseNominalInputData::~NetExportBaseNominalInputData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Default constructs the NetExportBaseNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportBaseNominal::NetExportBaseNominal(const std::string& name)
    :
    GunnsNetworkBase(name, N_NODES, netNodes),
    netNodes(),
    netConfig(name, this),
    netInput(this),
    // Data Tables
    DataTable(DataTableX, DataTableY, 1, 5.0, 5.0),
    // Spotters
    TestSpotter(),
    // Jumper Plugs
    testJumperPlug0(name + ".testJumperPlug0"),
    testJumperPlug1(name + ".testJumperPlug1"),
    // Links
    testSource(),
    testConductor(),
    testPotential(),
    GroundSocket(),
    TestCapacitor(),
    textExtSource(),
    testExtDemand(),
    testJumper()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details Default destructs the NetExportBaseNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportBaseNominal::~NetExportBaseNominal()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Initializes the nodes with their config and input data objects.  The nodes are
///           initialized through the node list object, which may point to this network's nodes
///           (when this is a standalone network), or the super-network's nodes (as a sub-network).
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportBaseNominal::initNodes(const std::string& name)
{
    /// - Initialize the nodes.
    netNodeList.mNodes[0 + netSuperNodesOffset].initialize(name + createNodeName(0 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[1 + netSuperNodesOffset].initialize(name + createNodeName(1 + netSuperNodesOffset), 10.0);
    netNodeList.mNodes[2 + netSuperNodesOffset].initialize(name + createNodeName(2 + netSuperNodesOffset), 10.0);
    netNodeList.mNodes[3 + netSuperNodesOffset].initialize(name + createNodeName(3 + netSuperNodesOffset), 0.0);
    netNodeList.mNodes[4 + netSuperNodesOffset].initialize(name + createNodeName(4 + netSuperNodesOffset), 0.0);
    /// - Only init the Ground node if this is not a sub-network.
    if (!netIsSubNetwork) {
        netNodeList.mNodes[5].initialize(name + ".GROUND");
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Initializes this network's links, spotters and solver with their config and input data
///           objects.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportBaseNominal::initNetwork()
{
    const int groundOffset = netNodeList.mNumNodes - N_NODES;

    /// - Register sockets with the jumper plugs.
    testJumperPlug0.addSocket(GroundSocket);
    testJumperPlug1.addSocket(GroundSocket);

    /// - Initialize the links.
    netLinks.clear();
    testSource.initialize(netConfig.testSource, netInput.testSource, netLinks, Node0 + netSuperNodesOffset, Node1 + netSuperNodesOffset);
    testConductor.initialize(netConfig.testConductor, netInput.testConductor, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    testPotential.initialize(netConfig.testPotential, netInput.testPotential, netLinks, Node2 + netSuperNodesOffset, Node3 + netSuperNodesOffset);
    GroundSocket.initialize(netConfig.GroundSocket, netInput.GroundSocket, netLinks, GROUND + groundOffset, Node0 + netSuperNodesOffset);
    TestCapacitor.initialize(netConfig.TestCapacitor, netInput.TestCapacitor, netLinks, Node1 + netSuperNodesOffset, Node4 + netSuperNodesOffset);
    textExtSource.initialize(netConfig.textExtSource, netInput.textExtSource, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    testExtDemand.initialize(netConfig.testExtDemand, netInput.testExtDemand, netLinks, GROUND + groundOffset, Node3 + netSuperNodesOffset);
    testJumper.initialize(netConfig.testJumper, netInput.testJumper, netLinks, Node3 + netSuperNodesOffset, Node0 + netSuperNodesOffset);

    /// - Initialize the spotters.
    TestSpotter.initialize(&netConfig.TestSpotter, &netInput.TestSpotter);

    /// - Initialize the solver, only if this is not a sub-network.
    if (!netIsSubNetwork) {
        netSolver.initializeNodes(netNodeList);
        netSolver.initialize(netConfig.netSolver, netLinks);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters before solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportBaseNominal::stepSpottersPre(const double timeStep)
{
    /// - Step network spotters prior to solver step.
    TestSpotter.stepPreSolver(timeStep);
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in]   timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters after solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportBaseNominal::stepSpottersPost(const double timeStep)
{
    /// - Step network spotters after solver step.
    TestSpotter.stepPostSolver(timeStep);
}
