#ifndef NetExportPowerNominal_EXISTS
#define NetExportPowerNominal_EXISTS

/**
@file  NetExportPowerNominal.hh
@brief NetExportPowerNominal GUNNS Basic Network declarations.


@details
PURPOSE: (Provides classes for the NetExportPowerNominal GUNNS Basic Network.)

REFERENCES:
  ()

ASSUMPTIONS AND LIMITATIONS:
  ()

LIBRARY DEPENDENCY:
  ((NetExportPowerNominal.o))

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.5.0) (2025-11-19 09:14:34.773649))

@{
*/

#include "software/SimCompatibility/TsSimCompatibility.hh"
#include "core/network/GunnsNetworkBase.hh"
#include "aspects/electrical/Batt/GunnsElectBattery.hh"
#include "aspects/electrical/ConstantPowerLoad/EpsConstantPowerLoad.hh"
#include "aspects/electrical/Converter/GunnsElectConverterInput.hh"
#include "aspects/electrical/Converter/GunnsElectConverterOutput.hh"
#include "aspects/electrical/Diode/GunnsElectRealDiode.hh"
#include "aspects/electrical/SolarArray/GunnsElectPvArray.hh"
#include "aspects/electrical/SolarArray/GunnsElectPvRegConv.hh"
#include "aspects/electrical/SolarArray/GunnsElectPvRegShunt.hh"
#include "aspects/electrical/Switch/GunnsElectSelector.hh"
#include "aspects/electrical/Switch/GunnsElectUserLoadSwitch2.hh"
#include "aspects/electrical/Switch/SwitchElect.hh"
#include "aspects/electrical/resistive/GunnsElectShort.hh"
#include "aspects/electrical/resistive/GunnsElectricalResistor.hh"
#include "aspects/electrical/resistive/GunnsResistiveLoad.hh"
#include "aspects/electrical/resistive/GunnsResistorPowerFunction.hh"
#include "core/GunnsBasicFlowController.hh"

// Forward-declare the main network class for use in the config data.
class NetExportPowerNominal;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportPowerNominal GUNNS Network Config Data
///
/// @details  Configuration data class for the NetExportPowerNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportPowerNominalConfigData
{
    public:
        // Solver configuration data
        GunnsConfigData netSolver;    /**< (--) trick_chkpnt_io(**) Network solver config data. */
        // Spotters configuration data
        // Links configuration data
        GunnsElectBatteryConfigData TestBatt1;    /**< (--) trick_chkpnt_io(**) TestBatt1 config data. */
        GunnsElectBatteryConfigData TestBatt2;    /**< (--) trick_chkpnt_io(**) TestBatt2 config data. */
        GunnsElectUserLoadSwitch2ConfigData TestUserLoad;    /**< (--) trick_chkpnt_io(**) TestUserLoad config data. */
        SwitchElectConfigData TestSwitch;    /**< (--) trick_chkpnt_io(**) TestSwitch config data. */
        GunnsElectConverterInputConfigData TestCondIn;    /**< (--) trick_chkpnt_io(**) TestCondIn config data. */
        GunnsElectConverterOutputConfigData TestCondOut;    /**< (--) trick_chkpnt_io(**) TestCondOut config data. */
        GunnsElectPvArrayConfigData TestSolar1;    /**< (--) trick_chkpnt_io(**) TestSolar1 config data. */
        GunnsElectPvRegShuntConfigData TestShunt;    /**< (--) trick_chkpnt_io(**) TestShunt config data. */
        GunnsElectPvArrayConfigData TestSolar2;    /**< (--) trick_chkpnt_io(**) TestSolar2 config data. */
        GunnsElectPvRegConvConfigData TestConverter;    /**< (--) trick_chkpnt_io(**) TestConverter config data. */
        GunnsElectRealDiodeConfigData TestDiode;    /**< (--) trick_chkpnt_io(**) TestDiode config data. */
        EpsConstantPowerLoadConfigData TestPowerLoad;    /**< (--) trick_chkpnt_io(**) TestPowerLoad config data. */
        GunnsBasicFlowControllerConfigData TestCurrentLoad;    /**< (--) trick_chkpnt_io(**) TestCurrentLoad config data. */
        GunnsElectricalResistorConfigData TestResistor;    /**< (--) trick_chkpnt_io(**) TestResistor config data. */
        GunnsResistiveLoadConfigData TestResistiveLoad;    /**< (--) trick_chkpnt_io(**) TestResistiveLoad config data. */
        GunnsResistorPowerFunctionConfigData TestPowerFunction;    /**< (--) trick_chkpnt_io(**) TestPowerFunction config data. */
        GunnsElectSelectorConfigData TestSwitch1;    /**< (--) trick_chkpnt_io(**) TestSwitch1 config data. */
        GunnsElectSelectorConfigData TestSwitch2;    /**< (--) trick_chkpnt_io(**) TestSwitch2 config data. */
        GunnsElectShortConfigData TestShort;    /**< (--) trick_chkpnt_io(**) TestShort config data. */
        /// @brief  Default constructs this network configuration data.
        NetExportPowerNominalConfigData(const std::string& name, NetExportPowerNominal* network);
        /// @brief  Default destructs this network configuration data.
        virtual ~NetExportPowerNominalConfigData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportPowerNominalConfigData(const NetExportPowerNominalConfigData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportPowerNominalConfigData& operator =(const NetExportPowerNominalConfigData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportPowerNominal GUNNS Network Input Data
///
/// @details  Input data class for the NetExportPowerNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportPowerNominalInputData
{
    public:
        // Spotters input data
        // Links input data
        GunnsElectBatteryInputData TestBatt1;    /**< (--) trick_chkpnt_io(**) TestBatt1 input data. */
        GunnsElectBatteryInputData TestBatt2;    /**< (--) trick_chkpnt_io(**) TestBatt2 input data. */
        GunnsElectUserLoadSwitch2InputData TestUserLoad;    /**< (--) trick_chkpnt_io(**) TestUserLoad input data. */
        SwitchElectInputData TestSwitch;    /**< (--) trick_chkpnt_io(**) TestSwitch input data. */
        GunnsElectConverterInputInputData TestCondIn;    /**< (--) trick_chkpnt_io(**) TestCondIn input data. */
        GunnsElectConverterOutputInputData TestCondOut;    /**< (--) trick_chkpnt_io(**) TestCondOut input data. */
        GunnsElectPvArrayInputData TestSolar1;    /**< (--) trick_chkpnt_io(**) TestSolar1 input data. */
        GunnsElectPvRegShuntInputData TestShunt;    /**< (--) trick_chkpnt_io(**) TestShunt input data. */
        GunnsElectPvArrayInputData TestSolar2;    /**< (--) trick_chkpnt_io(**) TestSolar2 input data. */
        GunnsElectPvRegConvInputData TestConverter;    /**< (--) trick_chkpnt_io(**) TestConverter input data. */
        GunnsElectRealDiodeInputData TestDiode;    /**< (--) trick_chkpnt_io(**) TestDiode input data. */
        EpsConstantPowerLoadInputData TestPowerLoad;    /**< (--) trick_chkpnt_io(**) TestPowerLoad input data. */
        GunnsBasicFlowControllerInputData TestCurrentLoad;    /**< (--) trick_chkpnt_io(**) TestCurrentLoad input data. */
        GunnsElectricalResistorInputData TestResistor;    /**< (--) trick_chkpnt_io(**) TestResistor input data. */
        GunnsResistiveLoadInputData TestResistiveLoad;    /**< (--) trick_chkpnt_io(**) TestResistiveLoad input data. */
        GunnsResistorPowerFunctionInputData TestPowerFunction;    /**< (--) trick_chkpnt_io(**) TestPowerFunction input data. */
        GunnsElectSelectorInputData TestSwitch1;    /**< (--) trick_chkpnt_io(**) TestSwitch1 input data. */
        GunnsElectSelectorInputData TestSwitch2;    /**< (--) trick_chkpnt_io(**) TestSwitch2 input data. */
        GunnsElectShortInputData TestShort;    /**< (--) trick_chkpnt_io(**) TestShort input data. */
        /// @brief  Default constructs this network input data.
        NetExportPowerNominalInputData(NetExportPowerNominal* network);
        /// @brief  Default destructs this network input data.
        virtual ~NetExportPowerNominalInputData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportPowerNominalInputData(const NetExportPowerNominalInputData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportPowerNominalInputData& operator =(const NetExportPowerNominalInputData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    NetExportPowerNominal GUNNS Network
///
/// @details  Main class for the NetExportPowerNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class NetExportPowerNominal : public GunnsNetworkBase
{
    TS_MAKE_SIM_COMPATIBLE(NetExportPowerNominal);
    public:
        /// @brief  Enumeration of the NetExportPowerNominal Network nodes.
        enum Nodes
        {
            Node0 = 0,    ///< Node 0
            Node1 = 1,    ///< Node 1
            Node2 = 2,    ///< Node 2
            Node3 = 3,    ///< Node 3
            Node4 = 4,    ///< Node 4
            Node5 = 5,    ///< Node 5
            Node6 = 6,    ///< Node 6
            Node7 = 7,    ///< Node 7
            Node8 = 8,    ///< Node 8
            Node9 = 9,    ///< Node 9
            Node10 = 10,    ///< Node 10
            Node11 = 11,    ///< Node 11
            Node12 = 12,    ///< Node 12
            Node13 = 13,    ///< Node 13
            Node14 = 14,    ///< Node 14
            Node15 = 15,    ///< Node 15
            GROUND = 16,    ///< Ground Node
            N_NODES = 17    ///< Number of nodes including Ground
        };
        // Network declarations
        GunnsBasicNode netNodes[NetExportPowerNominal::N_NODES];    /**< (--) Network nodes array. */
        NetExportPowerNominalConfigData netConfig;    /**< (--) trick_chkpnt_io(**) Network config data. */
        NetExportPowerNominalInputData netInput;    /**< (--) trick_chkpnt_io(**) Network input data. */
        // Data Tables
        // Spotters
        // Links
        GunnsElectBattery TestBatt1;    /**< (--) TestBatt1 instance. */
        GunnsElectBattery TestBatt2;    /**< (--) TestBatt2 instance. */
        GunnsElectUserLoadSwitch2 TestUserLoad;    /**< (--) TestUserLoad instance. */
        SwitchElect TestSwitch;    /**< (--) TestSwitch instance. */
        GunnsElectConverterInput TestCondIn;    /**< (--) TestCondIn instance. */
        GunnsElectConverterOutput TestCondOut;    /**< (--) TestCondOut instance. */
        GunnsElectPvArray TestSolar1;    /**< (--) TestSolar1 instance. */
        GunnsElectPvRegShunt TestShunt;    /**< (--) TestShunt instance. */
        GunnsElectPvArray TestSolar2;    /**< (--) TestSolar2 instance. */
        GunnsElectPvRegConv TestConverter;    /**< (--) TestConverter instance. */
        GunnsElectRealDiode TestDiode;    /**< (--) TestDiode instance. */
        EpsConstantPowerLoad TestPowerLoad;    /**< (--) TestPowerLoad instance. */
        GunnsBasicFlowController TestCurrentLoad;    /**< (--) TestCurrentLoad instance. */
        GunnsElectricalResistor TestResistor;    /**< (--) TestResistor instance. */
        GunnsResistiveLoad TestResistiveLoad;    /**< (--) TestResistiveLoad instance. */
        GunnsResistorPowerFunction TestPowerFunction;    /**< (--) TestPowerFunction instance. */
        GunnsElectSelector TestSwitch1;    /**< (--) TestSwitch1 instance. */
        GunnsElectSelector TestSwitch2;    /**< (--) TestSwitch2 instance. */
        GunnsElectShort TestShort;    /**< (--) TestShort instance. */
        /// @brief  Default constructs this network.
        NetExportPowerNominal(const std::string& name = "");
        /// @brief  Default destructs this network.
        virtual ~NetExportPowerNominal();
        /// @brief  Network nodes initialization task.
        virtual void initNodes(const std::string& name);
        /// @brief  Network links & spotters initialization task.
        virtual void initNetwork();
        /// @brief  Update network spotters before the solver solution.
        virtual void stepSpottersPre(const double timeStep);
        /// @brief  Update network spotters after the solver solution.
        virtual void stepSpottersPost(const double timeStep);

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        NetExportPowerNominal(const NetExportPowerNominal&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        NetExportPowerNominal& operator =(const NetExportPowerNominal&);
};

/// @}

#endif
