/**
@file  NetExportFluidNominal.cpp
@brief NetExportFluidNominal GUNNS Fluid Network implementation.

LIBRARY DEPENDENCY:
(
  (aspects/fluid/capacitor/GunnsFluidAccum.o)
  (aspects/fluid/capacitor/GunnsFluidAccumGas.o)
  (aspects/fluid/capacitor/GunnsFluidTank.o)
  (aspects/fluid/conductor/GunnsFluid3WayCheckValve.o)
  (aspects/fluid/conductor/GunnsFluid3WayValve.o)
  (aspects/fluid/conductor/GunnsFluidCheckValve.o)
  (aspects/fluid/conductor/GunnsFluidLeak.o)
  (aspects/fluid/conductor/GunnsFluidSensor.o)
  (aspects/fluid/conductor/GunnsFluidValve.o)
  (aspects/fluid/potential/GunnsGasFan.o)
  (aspects/fluid/potential/GunnsLiquidCentrifugalPump.o)
  (aspects/fluid/source/GunnsFluidEvaporation.o)
  (aspects/fluid/source/GunnsGasDisplacementPump.o)
  (aspects/fluid/source/GunnsLiquidDisplacementPump.o)
  (core/GunnsFluidCapacitor.o)
  (core/GunnsFluidConductor.o)
  (core/GunnsFluidPotential.o)
  (core/GunnsFluidSource.o)
  (core/network/GunnsNetworkBase.o)
)

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.6.0) (2026-07-16 09:24:28.820072))
*/

#include "NetExportFluidNominal.hh"
#include "simulation/hs/TsHsMsg.hh"
#include "software/exceptions/TsInitializationException.hh"

/// @details  Loads constituent fluid types into the network's internal fluid types array.
FluidProperties::FluidType NetExportFluidNominalConfigData::netInternalFluidTypes[NetExportFluidNominalConfigData::N_INTERNAL_FLUIDS] =
{
    FluidProperties::GUNNS_O2,
    FluidProperties::GUNNS_N2,
    FluidProperties::GUNNS_H2O,
    FluidProperties::GUNNS_CO2
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name    (--) Name of the network for H&S messages.
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportFluidNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportFluidNominalConfigData::NetExportFluidNominalConfigData(const std::string& name, NetExportFluidNominal* network)
    :
    netSolver(name + ".netSolver", 0.001, 1.0e-8, 1, 1),
    // Spotter Config Data
    // Link Config Data
    vol0(name + ".vol0", &network->netNodeList, 0.0),
    TestPotential(name + ".TestPotential", &network->netNodeList, 0.0, 0.0),
    TestSource(name + ".TestSource", &network->netNodeList),
    vol1(name + ".vol1", &network->netNodeList, 0.0),
    vol2(name + ".vol2", &network->netNodeList, 0.0),
    TestValue(name + ".TestValue", &network->netNodeList, 0.5, 0.0, 0.0, 0.0, 0.0),
    TestTank(name + ".TestTank", &network->netNodeList, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0),
    TestCheckValve(name + ".TestCheckValve", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    Test3WayValve(name + ".Test3WayValve", &network->netNodeList, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    TestGasPump(name + ".TestGasPump", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, false),
    TestFan(name + ".TestFan", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 1.0, 0.0, 0.0, 0.0, false),
    TestLeak(name + ".TestLeak", &network->netNodeList, 0.1, 0.0),
    vol5(name + ".vol5", &network->netNodeList, 0.0),
    vol4(name + ".vol4", &network->netNodeList, 0.0),
    vol6(name + ".vol6", &network->netNodeList, 0.0),
    vol7(name + ".vol7", &network->netNodeList, 0.0),
    vol8(name + ".vol8", &network->netNodeList, 0.0),
    vol10(name + ".vol10", &network->netNodeList, 0.0),
    TestSource2(name + ".TestSource2", &network->netNodeList),
    TestGasAccum(name + ".TestGasAccum", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    3WayCheckValue(name + ".3WayCheckValue", &network->netNodeList, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    testGasFan(name + ".testGasFan", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 1.0, 0.0, 0.0, 0.0, false),
    vol9(name + ".vol9", &network->netNodeList, 0.0),
    vol12(name + ".vol12", &network->netNodeList, 0.0),
    TestLiquidPump(name + ".TestLiquidPump", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, false, FluidProperties::NO_FLUID, 0.0, 0.0),
    TestSpringAccum(name + ".TestSpringAccum", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    vol14(name + ".vol14", &network->netNodeList, 0.0),
    TestConductor(name + ".TestConductor", &network->netNodeList, 0.0, 0.0),
    vol15(name + ".vol15", &network->netNodeList, 0.0),
    TestLiquidCPump(name + ".TestLiquidCPump", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 1.0, 0.0, 0.0, 0.0, false, FluidProperties::NO_FLUID, 0.0, 0.0),
    vol16(name + ".vol16", &network->netNodeList, 0.0),
    TestLiquidEvaporator(name + ".TestLiquidEvaporator", &network->netNodeList, FluidProperties::GUNNS_H2O, 0.0, 0.0, 0),
    pt(name + ".pt", &network->netNodeList, 0.0, 0.0)
{
    // Load config data vectors
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportFluidNominal Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportFluidNominalConfigData::~NetExportFluidNominalConfigData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the NetExportFluidNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportFluidNominalInputData::NetExportFluidNominalInputData(NetExportFluidNominal* network)
    :
    FluidStateFractions(0.785, 0.2, 0.01, 0.005),
    FluidState(294.261, 101.325, 0.0, 0.0, FluidStateFractions.array, 0),
    FluidState2Fractions(1.0),
    FluidState2(294.261, 101.325, 0.0, 0.0, FluidState2Fractions.array, 0),
    // Spotter Input Data
    // Link Input Data
    vol0(false, 0.0, 0.5, FluidState),
    TestPotential(false, 0.0, 0.0),
    TestSource(false, 0.0, 0.1),
    vol1(false, 0.0, 0.5, FluidState),
    vol2(false, 0.0, 0.5, FluidState),
    TestValue(false, 0.0, 1.0, false, 0.0, 0.0),
    TestTank(false, 0.0, 0.5, FluidState, 0.0, 0.0),
    TestCheckValve(false, 0.0, 0.0, false, 0.0, 0.0, 0.0, false, 0.0),
    Test3WayValve(0.0, 0.0, 0.0),
    TestGasPump(false, 0.0, 0.0, 0.0, 0.0),
    TestFan(false, 0.0, 0.0, 0.0, 0.0),
    TestLeak(false, 0.0, false, 0.0, false, 0.0),
    vol5(false, 0.0, 0.5, FluidState),
    vol4(false, 0.0, 0.5, FluidState),
    vol6(false, 0.0, 0.5, FluidState),
    vol7(false, 0.0, 0.5, FluidState),
    vol8(false, 0.0, 0.5, FluidState),
    vol10(false, 0.0, 0.5, FluidState2),
    TestSource2(false, 0.0, 0.1),
    TestGasAccum(false, 0.0, 0.0, 0, 0, 0.0),
    3WayCheckValue(0.0, 0.0, 0.0, false, false, 0.0),
    testGasFan(false, 0.0, 0.0, 0.0, 0.0),
    vol9(false, 0.0, 2.0, FluidState),
    vol12(false, 0.0, 0.5, FluidState2),
    TestLiquidPump(false, 0.0, 0.0, 0.0, 0.0, false),
    TestSpringAccum(false, 0.0, 0.0, 0, 0.0),
    vol14(false, 0.0, 0.5, FluidState2),
    TestConductor(false, 0.0),
    vol15(false, 0.0, 0.5, FluidState2),
    TestLiquidCPump(false, 0.0, 0.0, 0.0, 0.0, false),
    vol16(false, 0.0, 0.5, FluidState2),
    TestLiquidEvaporator(false, 0.0, 0.0, 0.0, 0.0),
    pt(false, 0.0)
{
    // Load input data vectors
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the NetExportFluidNominal Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportFluidNominalInputData::~NetExportFluidNominalInputData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Default constructs the NetExportFluidNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportFluidNominal::NetExportFluidNominal(const std::string& name)
    :
    GunnsNetworkBase(name, N_NODES, netNodes),
    netNodes(),
    netConfig(name, this),
    netInput(this),
    netFluidProperties(),
    netInternalFluidConfig(&netFluidProperties, netConfig.netInternalFluidTypes, NetExportFluidNominalConfigData::N_INTERNAL_FLUIDS),
    // Data Tables
    // Spotters
    // Links
    vol0(),
    TestPotential(),
    TestSource(),
    vol1(),
    vol2(),
    TestValue(),
    TestTank(),
    TestCheckValve(),
    Test3WayValve(),
    TestGasPump(),
    TestFan(),
    TestLeak(),
    vol5(),
    vol4(),
    vol6(),
    vol7(),
    vol8(),
    vol10(),
    TestSource2(),
    TestGasAccum(),
    3WayCheckValue(),
    testGasFan(),
    vol9(),
    vol12(),
    TestLiquidPump(),
    TestSpringAccum(),
    vol14(),
    TestConductor(),
    vol15(),
    TestLiquidCPump(),
    vol16(),
    TestLiquidEvaporator(),
    pt()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details Default destructs the NetExportFluidNominal Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
NetExportFluidNominal::~NetExportFluidNominal()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Initializes the nodes with their config and input data objects.  The nodes are
///           initialized through the node list object, which may point to this network's nodes
///           (when this is a standalone network), or the super-network's nodes (as a sub-network).
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportFluidNominal::initNodes(const std::string& name)
{
    /// - Initialize the nodes.
    GunnsFluidNode* nodes = static_cast<GunnsFluidNode*>(netNodeList.mNodes);
    nodes[0 + netSuperNodesOffset].initialize(name + createNodeName(0 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[1 + netSuperNodesOffset].initialize(name + createNodeName(1 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[2 + netSuperNodesOffset].initialize(name + createNodeName(2 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[3 + netSuperNodesOffset].initialize(name + createNodeName(3 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[4 + netSuperNodesOffset].initialize(name + createNodeName(4 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[5 + netSuperNodesOffset].initialize(name + createNodeName(5 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[6 + netSuperNodesOffset].initialize(name + createNodeName(6 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[7 + netSuperNodesOffset].initialize(name + createNodeName(7 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[8 + netSuperNodesOffset].initialize(name + createNodeName(8 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[9 + netSuperNodesOffset].initialize(name + createNodeName(9 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState);
    nodes[10 + netSuperNodesOffset].initialize(name + createNodeName(10 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    nodes[11 + netSuperNodesOffset].initialize(name + createNodeName(11 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    nodes[12 + netSuperNodesOffset].initialize(name + createNodeName(12 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    nodes[13 + netSuperNodesOffset].initialize(name + createNodeName(13 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    nodes[14 + netSuperNodesOffset].initialize(name + createNodeName(14 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    nodes[15 + netSuperNodesOffset].initialize(name + createNodeName(15 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    nodes[16 + netSuperNodesOffset].initialize(name + createNodeName(16 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.FluidState2);
    /// - Only init the Ground node if this is not a sub-network.
    if (!netIsSubNetwork) {
        nodes[17].initialize(name + ".GROUND", &netInternalFluidConfig, 0);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Initializes this network's links, spotters and solver with their config and input data
///           objects.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportFluidNominal::initNetwork()
{
    const int groundOffset = netNodeList.mNumNodes - N_NODES;

    /// - Register sockets with the jumper plugs.

    /// - Initialize the links.
    netLinks.clear();
    vol0.initialize(netConfig.vol0, netInput.vol0, netLinks, Node0 + netSuperNodesOffset, GROUND + groundOffset);
    TestPotential.initialize(netConfig.TestPotential, netInput.TestPotential, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    TestSource.initialize(netConfig.TestSource, netInput.TestSource, netLinks, Node0 + netSuperNodesOffset, Node1 + netSuperNodesOffset);
    vol1.initialize(netConfig.vol1, netInput.vol1, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    vol2.initialize(netConfig.vol2, netInput.vol2, netLinks, Node2 + netSuperNodesOffset, GROUND + groundOffset);
    TestValue.initialize(netConfig.TestValue, netInput.TestValue, netLinks, Node2 + netSuperNodesOffset, Node3 + netSuperNodesOffset);
    TestTank.initialize(netConfig.TestTank, netInput.TestTank, netLinks, Node3 + netSuperNodesOffset, GROUND + groundOffset);
    TestCheckValve.initialize(netConfig.TestCheckValve, netInput.TestCheckValve, netLinks, Node3 + netSuperNodesOffset, Node4 + netSuperNodesOffset);
    Test3WayValve.initialize(netConfig.Test3WayValve, netInput.Test3WayValve, netLinks, Node4 + netSuperNodesOffset, Node6 + netSuperNodesOffset, Node5 + netSuperNodesOffset);
    TestGasPump.initialize(netConfig.TestGasPump, netInput.TestGasPump, netLinks, Node5 + netSuperNodesOffset, Node7 + netSuperNodesOffset);
    TestFan.initialize(netConfig.TestFan, netInput.TestFan, netLinks, Node7 + netSuperNodesOffset, Node8 + netSuperNodesOffset);
    TestLeak.initialize(netConfig.TestLeak, netInput.TestLeak, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    vol5.initialize(netConfig.vol5, netInput.vol5, netLinks, Node5 + netSuperNodesOffset, GROUND + groundOffset);
    vol4.initialize(netConfig.vol4, netInput.vol4, netLinks, Node4 + netSuperNodesOffset, GROUND + groundOffset);
    vol6.initialize(netConfig.vol6, netInput.vol6, netLinks, Node6 + netSuperNodesOffset, GROUND + groundOffset);
    vol7.initialize(netConfig.vol7, netInput.vol7, netLinks, Node7 + netSuperNodesOffset, GROUND + groundOffset);
    vol8.initialize(netConfig.vol8, netInput.vol8, netLinks, Node8 + netSuperNodesOffset, GROUND + groundOffset);
    vol10.initialize(netConfig.vol10, netInput.vol10, netLinks, Node10 + netSuperNodesOffset, GROUND + groundOffset);
    TestSource2.initialize(netConfig.TestSource2, netInput.TestSource2, netLinks, Node10 + netSuperNodesOffset, Node11 + netSuperNodesOffset);
    TestGasAccum.initialize(netConfig.TestGasAccum, netInput.TestGasAccum, netLinks, Node1 + netSuperNodesOffset, Node11 + netSuperNodesOffset);
    3WayCheckValue.initialize(netConfig.3WayCheckValue, netInput.3WayCheckValue, netLinks, Node11 + netSuperNodesOffset, Node13 + netSuperNodesOffset, Node14 + netSuperNodesOffset);
    testGasFan.initialize(netConfig.testGasFan, netInput.testGasFan, netLinks, Node9 + netSuperNodesOffset, Node6 + netSuperNodesOffset);
    vol9.initialize(netConfig.vol9, netInput.vol9, netLinks, Node9 + netSuperNodesOffset, GROUND + groundOffset);
    vol12.initialize(netConfig.vol12, netInput.vol12, netLinks, Node12 + netSuperNodesOffset, GROUND + groundOffset);
    TestLiquidPump.initialize(netConfig.TestLiquidPump, netInput.TestLiquidPump, netLinks, Node12 + netSuperNodesOffset, Node13 + netSuperNodesOffset);
    TestSpringAccum.initialize(netConfig.TestSpringAccum, netInput.TestSpringAccum, netLinks, GROUND + groundOffset, Node13 + netSuperNodesOffset);
    vol14.initialize(netConfig.vol14, netInput.vol14, netLinks, Node14 + netSuperNodesOffset, GROUND + groundOffset);
    TestConductor.initialize(netConfig.TestConductor, netInput.TestConductor, netLinks, Node14 + netSuperNodesOffset, Node15 + netSuperNodesOffset);
    vol15.initialize(netConfig.vol15, netInput.vol15, netLinks, Node15 + netSuperNodesOffset, GROUND + groundOffset);
    TestLiquidCPump.initialize(netConfig.TestLiquidCPump, netInput.TestLiquidCPump, netLinks, Node15 + netSuperNodesOffset, Node16 + netSuperNodesOffset);
    vol16.initialize(netConfig.vol16, netInput.vol16, netLinks, Node16 + netSuperNodesOffset, GROUND + groundOffset);
    TestLiquidEvaporator.initialize(netConfig.TestLiquidEvaporator, netInput.TestLiquidEvaporator, netLinks, Node16 + netSuperNodesOffset, Node9 + netSuperNodesOffset);
    pt.initialize(netConfig.pt, netInput.pt, netLinks, Node14 + netSuperNodesOffset, GROUND + groundOffset);

    /// - Initialize the spotters.

    /// - Initialize the solver, only if this is not a sub-network.
    if (!netIsSubNetwork) {
        netSolver.initializeFluidNodes(netNodeList);
        netSolver.initialize(netConfig.netSolver, netLinks);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters before solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportFluidNominal::stepSpottersPre(const double timeStep)
{
    /// - Step network spotters prior to solver step.
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in]   timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters after solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void NetExportFluidNominal::stepSpottersPost(const double timeStep)
{
    /// - Step network spotters after solver step.
}
