#!/bin/tcsh

# TRICK_HOME setup
set TRICK_DEFAULT_PATH=/users/cxtfcm/TRICK_DB/10.10.0-dmtcp3-p1/trick
set TRICK_DEFAULT_VER=10.10.0
if ( ! $?TRICK_HOME ) then
  if ( -e ${TRICK_DEFAULT_PATH} ) then
     setenv TRICK_HOME ${TRICK_DEFAULT_PATH}
     setenv TRICK_VER ${TRICK_DEFAULT_VER}
  else
     echo "TRICK_HOME has not been set and $TRICK_DEFAULT_PATH does not exist\!\!"
     exit
  endif
endif

setenv TRICK_CFLAGS ""
if ( -e "$TRICK_HOME/bin/Trick.cshrc" ) then
    source "$TRICK_HOME/bin/Trick.cshrc"
endif

# GUNNS_HOME Setup.
setenv GUNNS_HOME `pwd`/..
setenv TRICK_CFLAGS "$TRICK_CFLAGS -I$GUNNS_HOME"
# TS_UTILS_HOME Setup
setenv TS_UTILS_HOME  "${GUNNS_HOME}/ts-utils"
setenv TRICK_CFLAGS "$TRICK_CFLAGS -I$TS_UTILS_HOME"

# sqlite and glib (for TS H&S)
#setenv TRICK_CFLAGS "${TRICK_CFLAGS} `pkg-config --cflags glib-2.0 sqlite3`"
#setenv TRICK_USER_LINK_LIBS "${TRICK_USER_LINK_LIBS} `pkg-config --libs-only-l glib-2.0 sqlite3`"

setenv TRICK_USER_LINK_LIBS "${TRICK_USER_LINK_LIBS} -ltinyxml"

# default TS H&S config file location
setenv HS_CONFIG_PATH "${GUNNS_HOME}/sims/Modified_data"
