#ifndef CPPSAFluidNetwork_EXISTS
#define CPPSAFluidNetwork_EXISTS

/**
@file  CPPSAFluidNetwork.hh
@brief CPPSAFluidNetwork GUNNS Fluid Network declarations.


@details
PURPOSE: (Provides classes for the CPPSAFluidNetwork GUNNS Fluid Network.)

REFERENCES:
  ()

ASSUMPTIONS AND LIMITATIONS:
  ((In the real world, the PCPA converts steam condensate from the DA to a mixture of steam condensate and urine distillate.
However, the SteamCondensateUrineDistillate liquid state isn't used in the network because GUNNS doesn't support
two-phase flow. This means that although a liquid and gas may be present in the same network, they may not both be
present in the same node or flow.))

LIBRARY DEPENDENCY:
  ((CPPSAFluidNetwork.o))

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.5.0) (2026-04-16 11:12:11.227073))

@{
*/

#include "software/SimCompatibility/TsSimCompatibility.hh"
#include "core/network/GunnsNetworkBase.hh"
#include "aspects/fluid/capacitor/GunnsFluidTank.hh"
#include "aspects/fluid/conductor/GunnsFluidCheckValve.hh"
#include "aspects/fluid/conductor/GunnsFluidCondensingHxSeparator.hh"
#include "aspects/fluid/conductor/GunnsFluidReliefValve.hh"
#include "aspects/fluid/conductor/GunnsFluidSensor.hh"
#include "aspects/fluid/conductor/GunnsFluidValve.hh"
#include "aspects/fluid/source/GunnsFluidMultiSeparator.hh"
#include "aspects/fluid/source/GunnsGasDisplacementPump.hh"
#include "core/GunnsFluidCapacitor.hh"

// Forward-declare the main network class for use in the config data.
class CPPSAFluidNetwork;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief  Data structure for CPPSAFluidNetwork GUNNS network mass fractions.
////////////////////////////////////////////////////////////////////////////////////////////////////
typedef struct CPPSAFluidNetworkFractions {
    double GUNNS_H2O;
    double GUNNS_WATER;
} CPPSAFluidNetworkFractions;

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief  Union for CPPSAFluidNetwork GUNNS network mass fractions as scalars and as an array.
///         The array is used as an argument in the PolyFluidInputData constructor.
////////////////////////////////////////////////////////////////////////////////////////////////////
union CPPSAFluidNetworkMassFractions {
    CPPSAFluidNetworkFractions scalar;
    double array[sizeof(CPPSAFluidNetworkFractions)/sizeof(double)];
    CPPSAFluidNetworkMassFractions(
        const double iGUNNS_H2O,
        const double iGUNNS_WATER);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    CPPSAFluidNetwork GUNNS Network Config Data
///
/// @details  Configuration data class for the CPPSAFluidNetwork Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class CPPSAFluidNetworkConfigData
{
    public:
        /// @brief  Enumeration of the number of internal constituent fluids in this network.
        enum {N_INTERNAL_FLUIDS = 2};
        // Network fluid configurations
        static FluidProperties::FluidType netInternalFluidTypes[CPPSAFluidNetworkConfigData::N_INTERNAL_FLUIDS];    /**< (--) trick_chkpnt_io(**) Network internal fluid types array. */
        // Solver configuration data
        GunnsConfigData netSolver;    /**< (--) trick_chkpnt_io(**) Network solver config data. */
        // Spotters configuration data
        // Links configuration data
        GunnsGasDisplacementPumpConfigData mclPurgePump2;    /**< (--) trick_chkpnt_io(**) mclPurgePump2 config data. */
        GunnsFluidCondensingHxSeparatorConfigData mclSPA;    /**< (--) trick_chkpnt_io(**) mclSPA config data. */
        GunnsFluidValveConfigData mclIsoValveAV01;    /**< (--) trick_chkpnt_io(**) mclIsoValveAV01 config data. */
        GunnsFluidSensorConfigData mclTempSenT23;    /**< (--) trick_chkpnt_io(**) mclTempSenT23 config data. */
        GunnsFluidCapacitorConfigData mclNode1Vol;    /**< (--) trick_chkpnt_io(**) mclNode1Vol config data. */
        GunnsFluidCapacitorConfigData mclNode2Vol;    /**< (--) trick_chkpnt_io(**) mclNode2Vol config data. */
        GunnsFluidCapacitorConfigData mclNode3Vol;    /**< (--) trick_chkpnt_io(**) mclNode3Vol config data. */
        GunnsFluidSensorConfigData mclPresSenP3A;    /**< (--) trick_chkpnt_io(**) mclPresSenP3A config data. */
        GunnsFluidSensorConfigData mclTempSenT20;    /**< (--) trick_chkpnt_io(**) mclTempSenT20 config data. */
        GunnsFluidSensorConfigData mclPresSenP4A;    /**< (--) trick_chkpnt_io(**) mclPresSenP4A config data. */
        GunnsFluidSensorConfigData mclPresSenP6A;    /**< (--) trick_chkpnt_io(**) mclPresSenP6A config data. */
        GunnsFluidSensorConfigData mclPresSenP4A_2;    /**< (--) trick_chkpnt_io(**) mclPresSenP4A_2 config data. */
        GunnsFluidReliefValveConfigData mclPresRelValvePR1;    /**< (--) trick_chkpnt_io(**) mclPresRelValvePR1 config data. */
        GunnsFluidCheckValveConfigData mclChkValveCV6;    /**< (--) trick_chkpnt_io(**) mclChkValveCV6 config data. */
        GunnsFluidSensorConfigData mclTempSenT16;    /**< (--) trick_chkpnt_io(**) mclTempSenT16 config data. */
        GunnsGasDisplacementPumpConfigData mclPurgePump1;    /**< (--) trick_chkpnt_io(**) mclPurgePump1 config data. */
        GunnsGasDisplacementPumpConfigData mclPurgePump3;    /**< (--) trick_chkpnt_io(**) mclPurgePump3 config data. */
        GunnsGasDisplacementPumpConfigData mclPurgePump4;    /**< (--) trick_chkpnt_io(**) mclPurgePump4 config data. */
        GunnsFluidCapacitorConfigData mclNode4Vol;    /**< (--) trick_chkpnt_io(**) mclNode4Vol config data. */
        GunnsFluidCapacitorConfigData mclNode5Vol;    /**< (--) trick_chkpnt_io(**) mclNode5Vol config data. */
        GunnsFluidCapacitorConfigData mclNode6Vol;    /**< (--) trick_chkpnt_io(**) mclNode6Vol config data. */
        GunnsFluidMultiSeparatorConfigData mclPurgeFilterF1;    /**< (--) trick_chkpnt_io(**) mclPurgeFilterF1 config data. */
        GunnsFluidTankConfigData mclFCPA;    /**< (--) trick_chkpnt_io(**) mclFCPA config data. */
        /// @brief  Default constructs this network configuration data.
        CPPSAFluidNetworkConfigData(const std::string& name, CPPSAFluidNetwork* network);
        /// @brief  Default destructs this network configuration data.
        virtual ~CPPSAFluidNetworkConfigData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        CPPSAFluidNetworkConfigData(const CPPSAFluidNetworkConfigData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        CPPSAFluidNetworkConfigData& operator =(const CPPSAFluidNetworkConfigData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    CPPSAFluidNetwork GUNNS Network Input Data
///
/// @details  Input data class for the CPPSAFluidNetwork Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class CPPSAFluidNetworkInputData
{
    public:
        // Internal network fluids
        CPPSAFluidNetworkMassFractions SteamCondensateFractions;    /**< (--) trick_chkpnt_io(**) Fluid mass fractions. */
        PolyFluidInputData SteamCondensate;    /**< (--) trick_chkpnt_io(**) Fluid input data. */
        CPPSAFluidNetworkMassFractions UrineDistillateFractions;    /**< (--) trick_chkpnt_io(**) Fluid mass fractions. */
        PolyFluidInputData UrineDistillate;    /**< (--) trick_chkpnt_io(**) Fluid input data. */
        CPPSAFluidNetworkMassFractions SteamCondensateUrineDistillateFractions;    /**< (--) trick_chkpnt_io(**) Fluid mass fractions. */
        PolyFluidInputData SteamCondensateUrineDistillate;    /**< (--) trick_chkpnt_io(**) Fluid input data. */
        // Spotters input data
        // Links input data
        GunnsGasDisplacementPumpInputData mclPurgePump2;    /**< (--) trick_chkpnt_io(**) mclPurgePump2 input data. */
        GunnsFluidCondensingHxSeparatorInputData mclSPA;    /**< (--) trick_chkpnt_io(**) mclSPA input data. */
        GunnsFluidValveInputData mclIsoValveAV01;    /**< (--) trick_chkpnt_io(**) mclIsoValveAV01 input data. */
        GunnsFluidSensorInputData mclTempSenT23;    /**< (--) trick_chkpnt_io(**) mclTempSenT23 input data. */
        GunnsFluidCapacitorInputData mclNode1Vol;    /**< (--) trick_chkpnt_io(**) mclNode1Vol input data. */
        GunnsFluidCapacitorInputData mclNode2Vol;    /**< (--) trick_chkpnt_io(**) mclNode2Vol input data. */
        GunnsFluidCapacitorInputData mclNode3Vol;    /**< (--) trick_chkpnt_io(**) mclNode3Vol input data. */
        GunnsFluidSensorInputData mclPresSenP3A;    /**< (--) trick_chkpnt_io(**) mclPresSenP3A input data. */
        GunnsFluidSensorInputData mclTempSenT20;    /**< (--) trick_chkpnt_io(**) mclTempSenT20 input data. */
        GunnsFluidSensorInputData mclPresSenP4A;    /**< (--) trick_chkpnt_io(**) mclPresSenP4A input data. */
        GunnsFluidSensorInputData mclPresSenP6A;    /**< (--) trick_chkpnt_io(**) mclPresSenP6A input data. */
        GunnsFluidSensorInputData mclPresSenP4A_2;    /**< (--) trick_chkpnt_io(**) mclPresSenP4A_2 input data. */
        GunnsFluidReliefValveInputData mclPresRelValvePR1;    /**< (--) trick_chkpnt_io(**) mclPresRelValvePR1 input data. */
        GunnsFluidCheckValveInputData mclChkValveCV6;    /**< (--) trick_chkpnt_io(**) mclChkValveCV6 input data. */
        GunnsFluidSensorInputData mclTempSenT16;    /**< (--) trick_chkpnt_io(**) mclTempSenT16 input data. */
        GunnsGasDisplacementPumpInputData mclPurgePump1;    /**< (--) trick_chkpnt_io(**) mclPurgePump1 input data. */
        GunnsGasDisplacementPumpInputData mclPurgePump3;    /**< (--) trick_chkpnt_io(**) mclPurgePump3 input data. */
        GunnsGasDisplacementPumpInputData mclPurgePump4;    /**< (--) trick_chkpnt_io(**) mclPurgePump4 input data. */
        GunnsFluidCapacitorInputData mclNode4Vol;    /**< (--) trick_chkpnt_io(**) mclNode4Vol input data. */
        GunnsFluidCapacitorInputData mclNode5Vol;    /**< (--) trick_chkpnt_io(**) mclNode5Vol input data. */
        GunnsFluidCapacitorInputData mclNode6Vol;    /**< (--) trick_chkpnt_io(**) mclNode6Vol input data. */
        GunnsFluidMultiSeparatorInputData mclPurgeFilterF1;    /**< (--) trick_chkpnt_io(**) mclPurgeFilterF1 input data. */
        GunnsFluidTankInputData mclFCPA;    /**< (--) trick_chkpnt_io(**) mclFCPA input data. */
        /// @brief  Default constructs this network input data.
        CPPSAFluidNetworkInputData(CPPSAFluidNetwork* network);
        /// @brief  Default destructs this network input data.
        virtual ~CPPSAFluidNetworkInputData();

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        CPPSAFluidNetworkInputData(const CPPSAFluidNetworkInputData&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        CPPSAFluidNetworkInputData& operator =(const CPPSAFluidNetworkInputData&);
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @brief    CPPSAFluidNetwork GUNNS Network
///
/// @details  Main class for the CPPSAFluidNetwork Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
class CPPSAFluidNetwork : public GunnsNetworkBase
{
    TS_MAKE_SIM_COMPATIBLE(CPPSAFluidNetwork);
    public:
        /// @brief  Enumeration of the CPPSAFluidNetwork Network nodes.
        enum Nodes
        {
            Node0 = 0,    ///< Node 0
            Node1 = 1,    ///< Node 1
            Node2 = 2,    ///< Node 2
            Node3 = 3,    ///< Node 3
            Node4 = 4,    ///< Node 4
            Node5 = 5,    ///< Node 5
            Node6 = 6,    ///< Node 6
            GROUND = 7,    ///< Ground Node
            N_NODES = 8    ///< Number of nodes including Ground
        };
        // Network declarations
        GunnsFluidNode netNodes[CPPSAFluidNetwork::N_NODES];    /**< (--) Network nodes array. */
        CPPSAFluidNetworkConfigData netConfig;    /**< (--) trick_chkpnt_io(**) Network config data. */
        CPPSAFluidNetworkInputData netInput;    /**< (--) trick_chkpnt_io(**) Network input data. */
        const DefinedFluidProperties netFluidProperties;        /**< (--) trick_chkpnt_io(**) Network defined fluid properties. */
        PolyFluidConfigData          netInternalFluidConfig;    /**< (--) trick_chkpnt_io(**) Network internal fluid config. */
        // Data Tables
        // Spotters
        // Links
        GunnsGasDisplacementPump mclPurgePump2;    /**< (--) mclPurgePump2 instance. */
        GunnsFluidCondensingHxSeparator mclSPA;    /**< (--) mclSPA instance. */
        GunnsFluidValve mclIsoValveAV01;    /**< (--) mclIsoValveAV01 instance. */
        GunnsFluidSensor mclTempSenT23;    /**< (--) mclTempSenT23 instance. */
        GunnsFluidCapacitor mclNode1Vol;    /**< (--) mclNode1Vol instance. */
        GunnsFluidCapacitor mclNode2Vol;    /**< (--) mclNode2Vol instance. */
        GunnsFluidCapacitor mclNode3Vol;    /**< (--) mclNode3Vol instance. */
        GunnsFluidSensor mclPresSenP3A;    /**< (--) mclPresSenP3A instance. */
        GunnsFluidSensor mclTempSenT20;    /**< (--) mclTempSenT20 instance. */
        GunnsFluidSensor mclPresSenP4A;    /**< (--) mclPresSenP4A instance. */
        GunnsFluidSensor mclPresSenP6A;    /**< (--) mclPresSenP6A instance. */
        GunnsFluidSensor mclPresSenP4A_2;    /**< (--) mclPresSenP4A_2 instance. */
        GunnsFluidReliefValve mclPresRelValvePR1;    /**< (--) mclPresRelValvePR1 instance. */
        GunnsFluidCheckValve mclChkValveCV6;    /**< (--) mclChkValveCV6 instance. */
        GunnsFluidSensor mclTempSenT16;    /**< (--) mclTempSenT16 instance. */
        GunnsGasDisplacementPump mclPurgePump1;    /**< (--) mclPurgePump1 instance. */
        GunnsGasDisplacementPump mclPurgePump3;    /**< (--) mclPurgePump3 instance. */
        GunnsGasDisplacementPump mclPurgePump4;    /**< (--) mclPurgePump4 instance. */
        GunnsFluidCapacitor mclNode4Vol;    /**< (--) mclNode4Vol instance. */
        GunnsFluidCapacitor mclNode5Vol;    /**< (--) mclNode5Vol instance. */
        GunnsFluidCapacitor mclNode6Vol;    /**< (--) mclNode6Vol instance. */
        GunnsFluidMultiSeparator mclPurgeFilterF1;    /**< (--) mclPurgeFilterF1 instance. */
        GunnsFluidTank mclFCPA;    /**< (--) mclFCPA instance. */
        /// @brief  Default constructs this network.
        CPPSAFluidNetwork(const std::string& name = "");
        /// @brief  Default destructs this network.
        virtual ~CPPSAFluidNetwork();
        /// @brief  Network nodes initialization task.
        virtual void initNodes(const std::string& name);
        /// @brief  Network links & spotters initialization task.
        virtual void initNetwork();
        /// @brief  Update network spotters before the solver solution.
        virtual void stepSpottersPre(const double timeStep);
        /// @brief  Update network spotters after the solver solution.
        virtual void stepSpottersPost(const double timeStep);
        /// @brief  Returns this network's fluid configuration.
        virtual const PolyFluidConfigData* getFluidConfig() const;

    private:
        /// @details  Copy constructor unavailable since declared private and not implemented.
        CPPSAFluidNetwork(const CPPSAFluidNetwork&);
        /// @details  Assignment operator unavailable since declared private and not implemented.
        CPPSAFluidNetwork& operator =(const CPPSAFluidNetwork&);
};

/// @}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @returns  PolyFluidConfigData* (--) Pointer to this network's fluid configuration.
///
/// @details  Returns this network's fluid configuration.
////////////////////////////////////////////////////////////////////////////////////////////////////
inline const PolyFluidConfigData* CPPSAFluidNetwork::getFluidConfig() const
{
    return &netInternalFluidConfig;
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] iGUNNS_H2O (--) Mass fraction of the GUNNS_H2O constituent in the composite fluid.
/// @param[in] iGUNNS_WATER (--) Mass fraction of the GUNNS_WATER constituent in the composite fluid.
///
/// @details  Constructs the mass fraction union from the scalar mass fraction arguments.
////////////////////////////////////////////////////////////////////////////////////////////////////
inline CPPSAFluidNetworkMassFractions::CPPSAFluidNetworkMassFractions (
    const double iGUNNS_H2O,
    const double iGUNNS_WATER)
{
    scalar.GUNNS_H2O = iGUNNS_H2O;
    scalar.GUNNS_WATER = iGUNNS_WATER;
}

#endif
