/**
@file  CPPSAFluidNetwork.cpp
@brief CPPSAFluidNetwork GUNNS Fluid Network implementation.

LIBRARY DEPENDENCY:
(
  (aspects/fluid/capacitor/GunnsFluidTank.o)
  (aspects/fluid/conductor/GunnsFluidCheckValve.o)
  (aspects/fluid/conductor/GunnsFluidCondensingHxSeparator.o)
  (aspects/fluid/conductor/GunnsFluidReliefValve.o)
  (aspects/fluid/conductor/GunnsFluidSensor.o)
  (aspects/fluid/conductor/GunnsFluidValve.o)
  (aspects/fluid/source/GunnsFluidMultiSeparator.o)
  (aspects/fluid/source/GunnsGasDisplacementPump.o)
  (core/GunnsFluidCapacitor.o)
  (core/network/GunnsNetworkBase.o)
)

PROGRAMMERS:
  ((Auto-generated by the GunnsDraw netexport script version 19.5.0) (2026-04-16 11:12:11.227073))
*/

#include "CPPSAFluidNetwork.hh"
#include "simulation/hs/TsHsMsg.hh"
#include "software/exceptions/TsInitializationException.hh"

/// @details  Loads constituent fluid types into the network's internal fluid types array.
FluidProperties::FluidType CPPSAFluidNetworkConfigData::netInternalFluidTypes[CPPSAFluidNetworkConfigData::N_INTERNAL_FLUIDS] =
{
    FluidProperties::GUNNS_H2O,
    FluidProperties::GUNNS_WATER
};

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name    (--) Name of the network for H&S messages.
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the CPPSAFluidNetwork Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
CPPSAFluidNetworkConfigData::CPPSAFluidNetworkConfigData(const std::string& name, CPPSAFluidNetwork* network)
    :
    netSolver(name + ".netSolver", 0.001, 1.0e-8, 1, 1),
    // Spotter Config Data
    // Link Config Data
    mclPurgePump2(name + ".mclPurgePump2", &network->netNodeList, 4.0, 4.0, 4.0, 4.0, 4.0, false),
    mclSPA(name + ".mclSPA", &network->netNodeList, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    mclIsoValveAV01(name + ".mclIsoValveAV01", &network->netNodeList, 5.0e-5, 0.0, 0.0, 0.0, 0.0),
    mclTempSenT23(name + ".mclTempSenT23", &network->netNodeList, 0.0, 0.0),
    mclNode1Vol(name + ".mclNode1Vol", &network->netNodeList, 0.0),
    mclNode2Vol(name + ".mclNode2Vol", &network->netNodeList, 0.0),
    mclNode3Vol(name + ".mclNode3Vol", &network->netNodeList, 0.0),
    mclPresSenP3A(name + ".mclPresSenP3A", &network->netNodeList, 0.0, 0.0),
    mclTempSenT20(name + ".mclTempSenT20", &network->netNodeList, 0.0, 0.0),
    mclPresSenP4A(name + ".mclPresSenP4A", &network->netNodeList, 0.0, 0.0),
    mclPresSenP6A(name + ".mclPresSenP6A", &network->netNodeList, 0.0, 0.0),
    mclPresSenP4A_2(name + ".mclPresSenP4A_2", &network->netNodeList, 0.0, 0.0),
    mclPresRelValvePR1(name + ".mclPresRelValvePR1", &network->netNodeList, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    mclChkValveCV6(name + ".mclChkValveCV6", &network->netNodeList, 5.0e-5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    mclTempSenT16(name + ".mclTempSenT16", &network->netNodeList, 0.0, 0.0),
    mclPurgePump1(name + ".mclPurgePump1", &network->netNodeList, 0.1, 0.1, 0.0, 0.0, 0.0, false),
    mclPurgePump3(name + ".mclPurgePump3", &network->netNodeList, 4.0, 4.0, 4.0, 4.0, 4.0, false),
    mclPurgePump4(name + ".mclPurgePump4", &network->netNodeList, 4.0, 4.0, 4.0, 4.0, 4.0, false),
    mclNode4Vol(name + ".mclNode4Vol", &network->netNodeList, 0.0),
    mclNode5Vol(name + ".mclNode5Vol", &network->netNodeList, 0.0),
    mclNode6Vol(name + ".mclNode6Vol", &network->netNodeList, 0.0),
    mclPurgeFilterF1(name + ".mclPurgeFilterF1", &network->netNodeList, 0.0, 0, 0, 0, 0),
    mclFCPA(name + ".mclFCPA", &network->netNodeList, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0)
{
    // Load config data vectors
    {
        const FluidProperties::FluidType array[] = {};
        mclPurgeFilterF1.mFluidTypes.assign(array, array + sizeof(array) / sizeof(FluidProperties::FluidType));
    }
    {
        const int array[] = {};
        mclPurgeFilterF1.mFluidPorts.assign(array, array + sizeof(array) / sizeof(int));
    }
    {
        const ChemicalCompound::Type array[] = {};
        mclPurgeFilterF1.mTcTypes.assign(array, array + sizeof(array) / sizeof(ChemicalCompound::Type));
    }
    {
        const int array[] = {};
        mclPurgeFilterF1.mTcPorts.assign(array, array + sizeof(array) / sizeof(int));
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the CPPSAFluidNetwork Network Config Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
CPPSAFluidNetworkConfigData::~CPPSAFluidNetworkConfigData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] network (--) Pointer to the main network object.
///
/// @details  Default constructs the CPPSAFluidNetwork Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
CPPSAFluidNetworkInputData::CPPSAFluidNetworkInputData(CPPSAFluidNetwork* network)
    :
    SteamCondensateFractions(1.0, 0.0),
    SteamCondensate(290.0, 120.0, 0.0, 1.0, SteamCondensateFractions.array, 0),
    UrineDistillateFractions(0.0, 1.0),
    UrineDistillate(290.0, 120.0, 0.0, 1.0, UrineDistillateFractions.array, 0),
    SteamCondensateUrineDistillateFractions(0.5, 0.5),
    SteamCondensateUrineDistillate(290.0, 120.0, 0.0, 1.0, SteamCondensateUrineDistillateFractions.array, 0),
    // Spotter Input Data
    // Link Input Data
    mclPurgePump2(false, 4.0, 4.0, 4.0, 4.0),
    mclSPA(false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, GunnsFluidCondensingHxSeparator::PAUSED_DRY),
    mclIsoValveAV01(false, 0.0, 1.0, false, 0.0, 0.0),
    mclTempSenT23(false, 0.0),
    mclNode1Vol(false, 0.0, 3.2e-4, &SteamCondensate),
    mclNode2Vol(false, 0.0, 3.2e-4, &SteamCondensate),
    mclNode3Vol(false, 0.0, 3.2e-4, &SteamCondensateUrineDistillate),
    mclPresSenP3A(false, 0.0),
    mclTempSenT20(false, 0.0),
    mclPresSenP4A(false, 0.0),
    mclPresSenP6A(false, 0.0),
    mclPresSenP4A_2(false, 0.0),
    mclPresRelValvePR1(false, 0.0, 0.0, false, 0.0, false, 0.0, 0.0, 0.0, false, false, 0.0),
    mclChkValveCV6(false, 0.0, 1.0, false, 0.0, 0.0, 0.0, false, 0.0),
    mclTempSenT16(false, 0.0),
    mclPurgePump1(false, 0.0, 0.0, 0.1, 0.0),
    mclPurgePump3(false, 4.0, 4.0, 4.0, 4.0),
    mclPurgePump4(false, 4.0, 4.0, 4.0, 4.0),
    mclNode4Vol(false, 0.0, 3.2e-4, &UrineDistillate),
    mclNode5Vol(false, 0.0, 3.2e-4, &UrineDistillate),
    mclNode6Vol(false, 0.0, 3.2e-4, &UrineDistillate),
    mclPurgeFilterF1(false, 0.0, 0, 0),
    mclFCPA(false, 0.0, 0.0, 0, 0.0, 0.0)
{
    // Load input data vectors
    {
        const double array[] = {};
        mclPurgeFilterF1.mFluidFractions.assign(array, array + sizeof(array) / sizeof(double));
    }
    {
        const double array[] = {};
        mclPurgeFilterF1.mTcFractions.assign(array, array + sizeof(array) / sizeof(double));
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Default destructs the CPPSAFluidNetwork Network Input Data.
////////////////////////////////////////////////////////////////////////////////////////////////////
CPPSAFluidNetworkInputData::~CPPSAFluidNetworkInputData()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Default constructs the CPPSAFluidNetwork Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
CPPSAFluidNetwork::CPPSAFluidNetwork(const std::string& name)
    :
    GunnsNetworkBase(name, N_NODES, netNodes),
    netNodes(),
    netConfig(name, this),
    netInput(this),
    netFluidProperties(),
    netInternalFluidConfig(&netFluidProperties, netConfig.netInternalFluidTypes, CPPSAFluidNetworkConfigData::N_INTERNAL_FLUIDS),
    // Data Tables
    // Spotters
    // Links
    mclPurgePump2(),
    mclSPA(),
    mclIsoValveAV01(),
    mclTempSenT23(),
    mclNode1Vol(),
    mclNode2Vol(),
    mclNode3Vol(),
    mclPresSenP3A(),
    mclTempSenT20(),
    mclPresSenP4A(),
    mclPresSenP6A(),
    mclPresSenP4A_2(),
    mclPresRelValvePR1(),
    mclChkValveCV6(),
    mclTempSenT16(),
    mclPurgePump1(),
    mclPurgePump3(),
    mclPurgePump4(),
    mclNode4Vol(),
    mclNode5Vol(),
    mclNode6Vol(),
    mclPurgeFilterF1(),
    mclFCPA()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details Default destructs the CPPSAFluidNetwork Network.
////////////////////////////////////////////////////////////////////////////////////////////////////
CPPSAFluidNetwork::~CPPSAFluidNetwork()
{
    // Nothing to do
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] name (--) Name of the network for H&S messages.
///
/// @details  Initializes the nodes with their config and input data objects.  The nodes are
///           initialized through the node list object, which may point to this network's nodes
///           (when this is a standalone network), or the super-network's nodes (as a sub-network).
////////////////////////////////////////////////////////////////////////////////////////////////////
void CPPSAFluidNetwork::initNodes(const std::string& name)
{
    /// - Initialize the nodes.
    GunnsFluidNode* nodes = static_cast<GunnsFluidNode*>(netNodeList.mNodes);
    nodes[0 + netSuperNodesOffset].initialize(name + createNodeName(0 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.SteamCondensate);
    nodes[1 + netSuperNodesOffset].initialize(name + createNodeName(1 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.SteamCondensate);
    nodes[2 + netSuperNodesOffset].initialize(name + createNodeName(2 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.SteamCondensate);
    nodes[3 + netSuperNodesOffset].initialize(name + createNodeName(3 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.SteamCondensate);
    nodes[4 + netSuperNodesOffset].initialize(name + createNodeName(4 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.UrineDistillate);
    nodes[5 + netSuperNodesOffset].initialize(name + createNodeName(5 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.UrineDistillate);
    nodes[6 + netSuperNodesOffset].initialize(name + createNodeName(6 + netSuperNodesOffset), &netInternalFluidConfig, &netInput.UrineDistillate);
    /// - Only init the Ground node if this is not a sub-network.
    if (!netIsSubNetwork) {
        nodes[7].initialize(name + ".GROUND", &netInternalFluidConfig, 0);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @details  Initializes this network's links, spotters and solver with their config and input data
///           objects.
////////////////////////////////////////////////////////////////////////////////////////////////////
void CPPSAFluidNetwork::initNetwork()
{
    const int groundOffset = netNodeList.mNumNodes - N_NODES;

    /// - Register sockets with the jumper plugs.

    /// - Initialize the links.
    netLinks.clear();
    mclPurgePump2.initialize(netConfig.mclPurgePump2, netInput.mclPurgePump2, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    mclSPA.initialize(netConfig.mclSPA, netInput.mclSPA, netLinks, Node3 + netSuperNodesOffset, Node4 + netSuperNodesOffset);
    mclIsoValveAV01.initialize(netConfig.mclIsoValveAV01, netInput.mclIsoValveAV01, netLinks, Node0 + netSuperNodesOffset, Node1 + netSuperNodesOffset);
    mclTempSenT23.initialize(netConfig.mclTempSenT23, netInput.mclTempSenT23, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    mclNode1Vol.initialize(netConfig.mclNode1Vol, netInput.mclNode1Vol, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    mclNode2Vol.initialize(netConfig.mclNode2Vol, netInput.mclNode2Vol, netLinks, Node2 + netSuperNodesOffset, GROUND + groundOffset);
    mclNode3Vol.initialize(netConfig.mclNode3Vol, netInput.mclNode3Vol, netLinks, Node3 + netSuperNodesOffset, GROUND + groundOffset);
    mclPresSenP3A.initialize(netConfig.mclPresSenP3A, netInput.mclPresSenP3A, netLinks, Node1 + netSuperNodesOffset, GROUND + groundOffset);
    mclTempSenT20.initialize(netConfig.mclTempSenT20, netInput.mclTempSenT20, netLinks, Node2 + netSuperNodesOffset, GROUND + groundOffset);
    mclPresSenP4A.initialize(netConfig.mclPresSenP4A, netInput.mclPresSenP4A, netLinks, Node2 + netSuperNodesOffset, GROUND + groundOffset);
    mclPresSenP6A.initialize(netConfig.mclPresSenP6A, netInput.mclPresSenP6A, netLinks, Node3 + netSuperNodesOffset, GROUND + groundOffset);
    mclPresSenP4A_2.initialize(netConfig.mclPresSenP4A_2, netInput.mclPresSenP4A_2, netLinks, Node3 + netSuperNodesOffset, GROUND + groundOffset);
    mclPresRelValvePR1.initialize(netConfig.mclPresRelValvePR1, netInput.mclPresRelValvePR1, netLinks, Node4 + netSuperNodesOffset, Node5 + netSuperNodesOffset, GROUND + groundOffset, GROUND + groundOffset);
    mclChkValveCV6.initialize(netConfig.mclChkValveCV6, netInput.mclChkValveCV6, netLinks, Node5 + netSuperNodesOffset, Node6 + netSuperNodesOffset);
    mclTempSenT16.initialize(netConfig.mclTempSenT16, netInput.mclTempSenT16, netLinks, Node6 + netSuperNodesOffset, GROUND + groundOffset);
    mclPurgePump1.initialize(netConfig.mclPurgePump1, netInput.mclPurgePump1, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    mclPurgePump3.initialize(netConfig.mclPurgePump3, netInput.mclPurgePump3, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    mclPurgePump4.initialize(netConfig.mclPurgePump4, netInput.mclPurgePump4, netLinks, Node1 + netSuperNodesOffset, Node2 + netSuperNodesOffset);
    mclNode4Vol.initialize(netConfig.mclNode4Vol, netInput.mclNode4Vol, netLinks, Node4 + netSuperNodesOffset, GROUND + groundOffset);
    mclNode5Vol.initialize(netConfig.mclNode5Vol, netInput.mclNode5Vol, netLinks, Node5 + netSuperNodesOffset, GROUND + groundOffset);
    mclNode6Vol.initialize(netConfig.mclNode6Vol, netInput.mclNode6Vol, netLinks, Node6 + netSuperNodesOffset, GROUND + groundOffset);
    {
        const int array[] = {Node2 + netSuperNodesOffset, Node3 + netSuperNodesOffset, GROUND + groundOffset};
        std::vector<int> vector (array, array + sizeof(array) / sizeof(int));
        mclPurgeFilterF1.initialize(netConfig.mclPurgeFilterF1, netInput.mclPurgeFilterF1, netLinks, &vector);
    }
    mclFCPA.initialize(netConfig.mclFCPA, netInput.mclFCPA, netLinks, Node6 + netSuperNodesOffset, GROUND + groundOffset);

    /// - Initialize the spotters.

    /// - Initialize the solver, only if this is not a sub-network.
    if (!netIsSubNetwork) {
        netSolver.initializeFluidNodes(netNodeList);
        netSolver.initialize(netConfig.netSolver, netLinks);
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in] timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters before solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void CPPSAFluidNetwork::stepSpottersPre(const double timeStep)
{
    /// - Step network spotters prior to solver step.
}

////////////////////////////////////////////////////////////////////////////////////////////////////
/// @param[in]   timeStep (s) Integration time step.
///
/// @details  Updates this network's spotters after solving the network.
////////////////////////////////////////////////////////////////////////////////////////////////////
void CPPSAFluidNetwork::stepSpottersPost(const double timeStep)
{
    /// - Step network spotters after solver step.
}
