#!/usr/bin/python

# Copyright 2019 United States Government as represented by the Administrator of the
# National Aeronautics and Space Administration.  All Rights Reserved.
#
import os
import sys

# Read a given valgrind log file, write all error suppression blocks to an output file
#
# They're all in a block like this:
# {
#    <insert_a_suppression_name_here>
#    ...
# }
#
# Example of use:
# $ python ./extract_valgrind_supressions.py <log file> <output file>
#
# The valgrind log file with suppressions can be generated by running valgrind on a
# unit test executable with these arguments added:
# --gen-suppressions=all --leak-check=full --log-file=<filename>
# Then this script is run on the output log file to extract just the suppression blocks.

count = 0

with open(sys.argv[2], 'w') as fout:
    with open(sys.argv[1], 'r') as fin:
        writeLine = False
        for line in fin:
            if ('{\n' == line and not writeLine):
                writeLine = True
            if ('}\n' == line and writeLine):
                writeLine = False
                fout.write(line + '\n')
                count = count + 1
            if (writeLine):
                fout.write(line)

print(sys.argv[2] + ' written with ' + str(count) + ' suppression blocks.')
