# Copyright 2019 United States Government as represented by the Administrator of the
# National Aeronautics and Space Administration.  All Rights Reserved.
no_TRICK_ENV = 1
include ${GUNNS_HOME}/test/utils/Makefile.default

